In [1]:
!pip install transformers 
!pip install protobuf==3.20.3

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.2.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->transformers) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17->transformers) (2024.2.0)
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 3.9 MB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.0
    Uninstalling protobuf-6.33.0:
      Successfully uninstalled protobuf-6.33.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.12.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
opentelemetry-proto 1.37.0 requires protobuf<7.0,>=5.0, but you have protobuf 3.20.3 which is incompatible.
onnx 1.18.0 requires protobuf>=4.25.1, but you have protobuf 3.20.3 which is incompatible.
a2a-sdk 0.3.10 requires protobuf>=5.29.5, but you have protobuf 3.20.3 which is incompatible.
ray 2.51.1 requires click!=8.3.0,>=7.0, but you have click 8.3.0 which is incompatible.
bigframes 2.12.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
tensorflow-metadata 1.17.2 requires protobuf>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.3 which is incompatible.
pydrive2 1.21.3 requires cryptography<44, but you have cryptography 46.0.3 which is incompatible.
pydrive2 1.21.3 requires pyOpenSSL<=24.2.1,>=19.1.0, but you have pyopenssl 25.3.0 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 3.20.3 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.10.0 which is incompatible.
Successfully installed protobuf-3.20.3

In [2]:
import pandas as pd 
import numpy as np 
import os 
import glob 
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
import timm # For pre-trained models
from tqdm import tqdm # For progress bars
from PIL import Image
import cv2

/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

In [3]:
import torch
from transformers import AutoImageProcessor, AutoModel

# This is the path to the dataset you added in Step 1
# The exact path may vary slightly based on which dataset you chose.
MODEL_PATH = '/kaggle/input/dinov2/pytorch/small/1' 
# Load the processor from the local files
processor = AutoImageProcessor.from_pretrained(MODEL_PATH)

# Load the model from the local files
model = AutoModel.from_pretrained(MODEL_PATH)
# --- Setup ---
device = torch.device("cuda")
model=model.to(device)
print(f"Using device: {device}")
model.eval()
print("DINOv2 model loaded successfully from local files.")

2025-12-17 06:32:40.922125: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1765953161.116825      20 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1765953161.175312      20 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Using device: cuda
DINOv2 model loaded successfully from local files.

In [4]:
print(f"Model is on: {next(model.parameters()).device}")

Model is on: cuda:0

In [5]:
BASE_PATH='/kaggle/input/csiro-biomass'
train_meta=pd.read_csv(os.path.join(BASE_PATH,'train.csv'))

In [6]:
# 1. Pivot the target variables
# (Pivoting on 'image_id' is a bit cleaner than the full path)
targets_df = train_meta.pivot(index='image_path', 
                              columns='target_name', 
                              values='target')

In [7]:
# 2. Get the unique metadata for each image
# (State, Species, etc. are repeated, so we just grab the first instance)
meta_df = train_meta[[  'image_path', 'Sampling_Date', 'State', 'Species',
       'Pre_GSHH_NDVI', 'Height_Ave_cm']] \
                      .drop_duplicates(subset='image_path') \
                      .set_index('image_path')

In [8]:
# 3. Join them together
# This creates one clean row per image with all data
train_df = meta_df.join(targets_df).reset_index()

In [9]:
train_df.columns

Index(['image_path', 'Sampling_Date', 'State', 'Species', 'Pre_GSHH_NDVI',
       'Height_Ave_cm', 'Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g',
       'Dry_Total_g', 'GDM_g'],
      dtype='object')

In [10]:
train_df[['Pre_GSHH_NDVI','Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g','Height_Ave_cm']].corr()

,Pre_GSHH_NDVI,Dry_Clover_g,Dry_Dead_g,Dry_Green_g,Height_Ave_cm
Pre_GSHH_NDVI,1.000000,0.224150,-0.122818,0.351054,0.238434
Dry_Clover_g,0.224150,1.000000,-0.175548,-0.276582,-0.160138
Dry_Dead_g,-0.122818,-0.175548,1.000000,0.095554,-0.049721
Dry_Green_g,0.351054,-0.276582,0.095554,1.000000,0.648439
Height_Ave_cm,0.238434,-0.160138,-0.049721,0.648439,1.000000

In [11]:
# 4. Define our 5 output targets
TARGET_COLS = list(train_df.columns[-5:-2])


# Weights: [Dry_Total_g, Dry_Green_g, Dry_Dead_g, Dry_Clover_g, Dry_Grass_g]
COMP_WEIGHTS = torch.tensor([0.5, 0.2, 0.1, 0.1,0.1]).to(device)

# Now train_df is ready!
print(train_df.head())

               image_path Sampling_Date State            Species  \
0  train/ID1011485656.jpg      2015/9/4   Tas    Ryegrass_Clover
1  train/ID1012260530.jpg      2015/4/1   NSW            Lucerne
2  train/ID1025234388.jpg      2015/9/1    WA  SubcloverDalkeith
3  train/ID1028611175.jpg     2015/5/18   Tas           Ryegrass
4  train/ID1035947949.jpg     2015/9/11   Tas           Ryegrass

   Pre_GSHH_NDVI  Height_Ave_cm  Dry_Clover_g  Dry_Dead_g  Dry_Green_g  \
0           0.62         4.6667        0.0000     31.9984      16.2751
1           0.55        16.0000        0.0000      0.0000       7.6000
2           0.38         1.0000        6.0500      0.0000       0.0000
3           0.66         5.0000        0.0000     30.9703      24.2376
4           0.54         3.5000        0.4343     23.2239      10.5261

   Dry_Total_g    GDM_g
0      48.2735  16.2750
1       7.6000   7.6000
2       6.0500   6.0500
3      55.2079  24.2376
4      34.1844  10.9605

In [12]:
train_df_sample = train_df

In [13]:
# Convert the string column to datetime objects
train_df_sample['date_temp'] = pd.to_datetime(train_df_sample['Sampling_Date'], format='%Y/%m/%d')

# Convert to a timestamp (seconds) or just an ordinal number
# This creates a float like 1685577600.0
train_df_sample['date_numeric'] = train_df_sample['date_temp'].map(pd.Timestamp.timestamp)

In [14]:
train_df_sample

,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,Dry_Clover_g,Dry_Dead_g,Dry_Green_g,Dry_Total_g,GDM_g,date_temp,date_numeric
0,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,0.0000,31.9984,16.2751,48.2735,16.2750,2015-09-04,1.441325e+09
1,train/ID1012260530.jpg,2015/4/1,NSW,Lucerne,0.55,16.0000,0.0000,0.0000,7.6000,7.6000,7.6000,2015-04-01,1.427846e+09
2,train/ID1025234388.jpg,2015/9/1,WA,SubcloverDalkeith,0.38,1.0000,6.0500,0.0000,0.0000,6.0500,6.0500,2015-09-01,1.441066e+09
3,train/ID1028611175.jpg,2015/5/18,Tas,Ryegrass,0.66,5.0000,0.0000,30.9703,24.2376,55.2079,24.2376,2015-05-18,1.431907e+09
4,train/ID1035947949.jpg,2015/9/11,Tas,Ryegrass,0.54,3.5000,0.4343,23.2239,10.5261,34.1844,10.9605,2015-09-11,1.441930e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,train/ID975115267.jpg,2015/7/8,WA,Clover,0.73,3.0000,40.0300,0.0000,0.8000,40.8300,40.8300,2015-07-08,1.436314e+09
353,train/ID978026131.jpg,2015/9/4,Tas,Clover,0.83,3.1667,24.6445,4.1948,12.0601,40.8994,36.7046,2015-09-04,1.441325e+09
354,train/ID980538882.jpg,2015/2/24,NSW,Phalaris,0.69,29.0000,0.0000,1.1457,91.6543,92.8000,91.6543,2015-02-24,1.424736e+09
355,train/ID980878870.jpg,2015/7/8,WA,Clover,0.74,2.0000,32.3575,0.0000,2.0325,34.3900,34.3900,2015-07-08,1.436314e+09
356,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,0.0000,0.0000,40.9400,40.9400,40.9400,2015-09-01,1.441066e+09

In [15]:
import torch
import cv2
import os
import numpy as np
from torch.utils.data import Dataset

class BiomassGPU_ExpandedDataset(Dataset):
    def __init__(self, df, target_cols, date_col, base_path, expand_factor=2):
        self.df = df
        self.image_paths = [os.path.join(base_path, p) for p in df['image_path']]
        self.labels = df[target_cols].values.astype(np.float32)
        # Assuming dates are pre-converted to float
        self.dates = df[date_col].values.astype(np.float32)
        self.ndvi = df['Pre_GSHH_NDVI'].values.astype(np.float32)
        self.real_length = len(self.image_paths)
        self.expand_factor = expand_factor
        self.state_codes = pd.Categorical(df['State']).codes
    def __len__(self):
        # Trick the loader: Length is Multiplied (e.g., 100 -> 200)
        return self.real_length * self.expand_factor

    def __getitem__(self, idx):
        # 1. Map Virtual Index -> Real Index
        real_idx = idx % self.real_length
        
        # 2. Determine Augmentation Status
        # If index is in the second half (or beyond), we mark it for augmentation
        augmentation_level = idx // self.real_length
        should_augment = (augmentation_level > 0)

        # 3. Load Raw Image (CPU)
        image_path = self.image_paths[real_idx]
        image = cv2.imread(image_path)
        if image is None: raise FileNotFoundError(f"{image_path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        # 4. Tile Left/Right
        height, width, _ = image.shape
        midpoint = width // 2 
        tile_left = image[:, 0:midpoint, :]
        tile_right = image[:, midpoint:width, :]
        
        # 5. Convert to Tensor (C, H, W) but NO processing yet
        left_tensor = torch.from_numpy(tile_left).permute(2, 0, 1)
        right_tensor = torch.from_numpy(tile_right).permute(2, 0, 1)

        labels = torch.tensor(self.labels[real_idx])
        date_tensor = torch.tensor(self.dates[real_idx], dtype=torch.float32)
        ndvi_val = torch.tensor(self.ndvi[real_idx], dtype=torch.float32)
        state_val = torch.tensor(self.state_codes[real_idx], dtype=torch.long)
        # 6. Return the "Augment Flag"
        # We pass this as a float (1.0 or 0.0) or long to use as a mask later
        aug_flag = torch.tensor(1 if should_augment else 0, dtype=torch.bool)

        return left_tensor, right_tensor, labels, date_tensor, aug_flag,ndvi_val,state_val

In [16]:
from torchvision.transforms import v2

# # # 1. Common Steps (Run on ALL images)
# # # Resize first to save GPU memory before other ops
# common_transform = v2.Compose([
#     v2.ToDtype(torch.float32, scale=True), # 0-255 -> 0.0-1.0
#     v2.Resize((224, 224), antialias=True),
# ])

# # # 2. Augmentation Steps (Run ONLY on "Expanded" images)
# # # This adds the Flips you asked for!
# # aug_transform = v2.Compose([
# #     v2.RandomHorizontalFlip(p=0.5),
# #     v2.RandomVerticalFlip(p=0.5),
# #     v2.RandomRotation(degrees=15),
# #     v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
# # ])

# mean=[0.485, 0.456, 0.406]
# std=[0.229, 0.224, 0.225]


# # common_transform = v2.Compose([ v2.ToDtype(torch.float32, scale=True), v2.Resize((224, 224)), v2.Normalize(mean, std)])
# aug_transform = 
#     [v2.Compose([ v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # Original
#     v2.Compose([v2.RandomHorizontalFlip(p=1.0), v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # Horizontal flip
#     v2.Compose([v2.RandomVerticalFlip(p=1.0), v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # Vertical flip
#     v2.Compose([v2.RandomHorizontalFlip(p=1.0), v2.RandomVerticalFlip(p=1.0), v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # Both flips
#     v2.Compose([v2.RandomRotation(degrees=90), v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # 90 degree rotation
#     v2.Compose([v2.RandomRotation(degrees=270),  v2.Resize((224, 224)), v2.Normalize(mean, std), v2.GaussianBlur(5)]),  # 270 degree rotation
#     ]

# # # 3. Final Step (Normalization for DINO)
# norm_transform = v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

In [17]:
# 1. Common Steps (Pre-processing)
# Apply Resize here so we don't repeat it later
common_transform = v2.Compose([
    v2.ToDtype(torch.float32, scale=True),
    v2.Resize((224, 224), antialias=True),
])

# 2. Augmentation Steps
# - REMOVED Resize (Done in common_transform)
# - REMOVED Normalize (Done in Step 4)
# - Wrapped in RandomChoice so it works like a single function
aug_transform = v2.RandomChoice([
    v2.GaussianBlur(kernel_size=5),                                     # 1. Original (just blur)
    v2.Compose([v2.RandomHorizontalFlip(p=1.0), v2.GaussianBlur(5)]),   # 2. H Flip
    v2.Compose([v2.RandomVerticalFlip(p=1.0), v2.GaussianBlur(5)]),     # 3. V Flip
    v2.Compose([                                                        # 4. Both Flips
        v2.RandomHorizontalFlip(p=1.0),
        v2.RandomVerticalFlip(p=1.0),
        v2.GaussianBlur(5)
    ]),
    v2.Compose([v2.RandomRotation(degrees=(90, 90)), v2.GaussianBlur(5)]),   # 5. Rot 90
    v2.Compose([v2.RandomRotation(degrees=(270, 270)), v2.GaussianBlur(5)]), # 6. Rot 270
])

# 3. Final Step (Normalization)
# This runs AFTER augmentation
norm_transform = v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

In [18]:
# --- 3. Create Datasets with new transforms ---
train_dataset = BiomassGPU_ExpandedDataset(df=train_df_sample, 
                               target_cols=TARGET_COLS, 
                               base_path=BASE_PATH,
                                date_col='date_numeric',
                               expand_factor=2) # <-- Pass transforms

In [19]:
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=4)

In [20]:
import torch
import numpy as np
import xgboost as xgb
from tqdm import tqdm
import pickle
import os
import pandas as pd

# Containers
all_features = []
all_labels = []
all_dates = []
all_ndvi = []
all_states = []

# Ensure model is in eval mode
dino_model = model.eval()

print(f"Starting Extraction on {len(train_dataset)} samples...")

for batch_left, batch_right, batch_labels, batch_dates, batch_aug_flags, ndvi_val,state_val in tqdm(train_loader):
    
    # 1. Move Images & Flags to GPU
    b_left = batch_left.to(device, non_blocking=True)
    b_right = batch_right.to(device, non_blocking=True)
    flags = batch_aug_flags.to(device, non_blocking=True) 
    
    # 2. Apply Transforms
    b_left = common_transform(b_left)
    b_right = common_transform(b_right)

    # 3. Augmentation (Masked)
    if flags.any():
        b_left[flags] = aug_transform(b_left[flags])
        b_right[flags] = aug_transform(b_right[flags])

    # 4. Normalize
    b_left = norm_transform(b_left)
    b_right = norm_transform(b_right)
    
    # 5. Inference
    with torch.no_grad():
        # USE CLS TOKEN (Index 0) - Cleaner features than pooler_output
        out_left = dino_model(pixel_values=b_left).last_hidden_state[:, 0, :]
        out_right = dino_model(pixel_values=b_right).last_hidden_state[:, 0, :]
    
    # 6. Concatenate & Collect
    combined_features = torch.cat((out_left, out_right), dim=1)
    
    all_features.append(combined_features.cpu().numpy())
    all_labels.append(batch_labels.numpy())
    all_dates.append(batch_dates.numpy())
    
    # CRITICAL FIX: Append CPU tensor directly, do not move to GPU
    all_ndvi.append(ndvi_val.numpy()) 
    all_states.append(state_val.numpy())
    

# Final Stack
X_raw = np.vstack(all_features)      # Shape: (N, 1536)
y_raw = np.vstack(all_labels)        # Shape: (N, 3)
ndvi_raw = np.concatenate(all_ndvi)  # Shape: (N,)
groups_raw = np.concatenate(all_dates)
state_raw=np.concatenate(all_states)

print(f"Extraction Complete. Feature Shape: {X_raw.shape}")

Starting Extraction on 714 samples...

100%|██████████| 45/45 [00:19<00:00,  2.36it/s]

Extraction Complete. Feature Shape: (714, 768)

### Auxillary task of Predicting NDVI

In [21]:
import os
import pickle
import json
import numpy as np
import pandas as pd
import xgboost as xgb
import optuna
from sklearn.model_selection import train_test_split, GroupKFold
from sklearn.metrics import mean_squared_error, r2_score
from functools import partial

# Create directory for models
MODEL_DIR = "saved_models"
os.makedirs(MODEL_DIR, exist_ok=True)

# ==========================================
# PART 1: NDVI PROXY MODEL (Optimization & Saving)
# ==========================================
print("\n" + "="*40)
print(" STEP 1: NDVI PROXY MODEL")
print("="*40)

# 1. Split for NDVI Optimization
X_opt_train, X_opt_val, y_opt_train, y_opt_val = train_test_split(
    X_raw, ndvi_raw, test_size=0.2, random_state=42
)

# 2. Define Objective (RMSE)
def objective_ndvi(trial):
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 1000, 3000, step=500),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
        'max_depth': trial.suggest_int('max_depth', 4, 10),
        'subsample': trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 3, 10),
        'tree_method': 'hist', 'device': 'cuda', 'n_jobs': -1,
        'objective': 'reg:squarederror', 'eval_metric': 'rmse'
    }
    
    # Quick internal split for early stopping
    tr_x, val_x, tr_y, val_y = train_test_split(X_opt_train, y_opt_train, test_size=0.2)
    
    model = xgb.XGBRegressor(**param)
    model.fit(tr_x, tr_y, eval_set=[(val_x, val_y)], early_stopping_rounds=50, verbose=False)
    
    return np.sqrt(mean_squared_error(val_y, model.predict(val_x)))

# 3. Run Optuna
study_ndvi = optuna.create_study(direction="minimize", study_name="NDVI_Proxy")
study_ndvi.optimize(objective_ndvi, n_trials=40)
print(f"Best NDVI RMSE: {study_ndvi.best_value:.5f}")

# 4. Train Final NDVI Model & Save
best_ndvi_params = study_ndvi.best_params
best_ndvi_params.update({'tree_method': 'hist', 'device': 'cuda', 'n_jobs': -1})

final_ndvi_model = xgb.XGBRegressor(**best_ndvi_params)
final_ndvi_model.fit(X_raw, ndvi_raw) # Fit on ALL data

# SAVE NDVI MODEL
ndvi_path = os.path.join(MODEL_DIR, "ndvi_proxy_model.pkl")
with open(ndvi_path, "wb") as f:
    pickle.dump(final_ndvi_model, f)
print(f"NDVI Model saved to: {ndvi_path}")

# 5. AUGMENT FEATURES (The "Proceed" Step)
# Predict NDVI for the whole dataset to use as a feature for Biomass
print("Augmenting features with Predicted NDVI...")
ndvi_preds = final_ndvi_model.predict(X_raw)
X_final = np.column_stack((X_raw, ndvi_preds)) # Shape becomes (N, 1537)
print(f"New Feature Shape: {X_final.shape}")

[I 2025-12-17 06:33:20,033] A new study created in memory with name: NDVI_Proxy

========================================
 STEP 1: NDVI PROXY MODEL
========================================

/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:160: UserWarning: [06:33:26] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)
[I 2025-12-17 06:33:26,544] Trial 0 finished with value: 0.06288640946149826 and parameters: {'n_estimators': 1500, 'learning_rate': 0.007197025033353604, 'max_depth': 7, 'subsample': 0.781432834404803, 'colsample_bytree': 0.7862511727576733, 'min_child_weight': 8}. Best is trial 0 with value: 0.06288640946149826.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:33:31,746] Trial 1 finished with value: 0.0614829882979393 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009213021661432785, 'max_depth': 6, 'subsample': 0.6446478018353607, 'colsample_bytree': 0.6342058711522717, 'min_child_weight': 5}. Best is trial 1 with value: 0.0614829882979393.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:33:40,772] Trial 2 finished with value: 0.0550946407020092 and parameters: {'n_estimators': 3000, 'learning_rate': 0.006993988806319156, 'max_depth': 9, 'subsample': 0.8273143298138915, 'colsample_bytree': 0.730584843848479, 'min_child_weight': 8}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:33:44,777] Trial 3 finished with value: 0.08059049397706985 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013240096319859358, 'max_depth': 6, 'subsample': 0.7129808017810805, 'colsample_bytree': 0.7444487363292189, 'min_child_weight': 3}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:33:50,297] Trial 4 finished with value: 0.06356710940599442 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008141579663835878, 'max_depth': 5, 'subsample': 0.7856641705610916, 'colsample_bytree': 0.8994834810478864, 'min_child_weight': 6}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:04,503] Trial 5 finished with value: 0.06910201162099838 and parameters: {'n_estimators': 3000, 'learning_rate': 0.007669683421234206, 'max_depth': 10, 'subsample': 0.730967652719003, 'colsample_bytree': 0.8875928890769091, 'min_child_weight': 3}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:11,039] Trial 6 finished with value: 0.06721703708171844 and parameters: {'n_estimators': 2500, 'learning_rate': 0.01685060951682152, 'max_depth': 7, 'subsample': 0.8532385172948096, 'colsample_bytree': 0.677175483783279, 'min_child_weight': 5}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:15,651] Trial 7 finished with value: 0.07643211632966995 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0054348893599719525, 'max_depth': 10, 'subsample': 0.651670954833816, 'colsample_bytree': 0.6711139886514463, 'min_child_weight': 9}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:20,135] Trial 8 finished with value: 0.07335775345563889 and parameters: {'n_estimators': 1000, 'learning_rate': 0.015804355929533144, 'max_depth': 7, 'subsample': 0.6668493451231966, 'colsample_bytree': 0.8779863855869685, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:28,592] Trial 9 finished with value: 0.07253851741552353 and parameters: {'n_estimators': 2500, 'learning_rate': 0.01334805053833687, 'max_depth': 7, 'subsample': 0.7305466480813297, 'colsample_bytree': 0.8692225064740903, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:32,181] Trial 10 finished with value: 0.0713191032409668 and parameters: {'n_estimators': 3000, 'learning_rate': 0.04408984482124926, 'max_depth': 9, 'subsample': 0.8962004592947898, 'colsample_bytree': 0.7616212896705077, 'min_child_weight': 10}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:33,919] Trial 11 finished with value: 0.07259884476661682 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03730489167572519, 'max_depth': 4, 'subsample': 0.8244290796360818, 'colsample_bytree': 0.6184079118777431, 'min_child_weight': 7}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:34,730] Trial 12 finished with value: 0.07390239089727402 and parameters: {'n_estimators': 2500, 'learning_rate': 0.09531487252558431, 'max_depth': 9, 'subsample': 0.6311180884874256, 'colsample_bytree': 0.6049412069227941, 'min_child_weight': 7}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:42,083] Trial 13 finished with value: 0.06520695984363556 and parameters: {'n_estimators': 1500, 'learning_rate': 0.00517695091737156, 'max_depth': 8, 'subsample': 0.6052112275043594, 'colsample_bytree': 0.6984118592415827, 'min_child_weight': 6}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:46,356] Trial 14 finished with value: 0.06201016157865524 and parameters: {'n_estimators': 1500, 'learning_rate': 0.009878431574347266, 'max_depth': 5, 'subsample': 0.6916664079158883, 'colsample_bytree': 0.8074125190742617, 'min_child_weight': 8}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:50,166] Trial 15 finished with value: 0.06661378592252731 and parameters: {'n_estimators': 2000, 'learning_rate': 0.028938227041528933, 'max_depth': 8, 'subsample': 0.7786260723269209, 'colsample_bytree': 0.7124902454556842, 'min_child_weight': 5}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:34:58,553] Trial 16 finished with value: 0.07281947880983353 and parameters: {'n_estimators': 3000, 'learning_rate': 0.010640535108011941, 'max_depth': 6, 'subsample': 0.8314758359811365, 'colsample_bytree': 0.6476096628875804, 'min_child_weight': 10}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:05,939] Trial 17 finished with value: 0.07964299619197845 and parameters: {'n_estimators': 2500, 'learning_rate': 0.022485158611013092, 'max_depth': 9, 'subsample': 0.8663296768758101, 'colsample_bytree': 0.834093007050233, 'min_child_weight': 8}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:07,694] Trial 18 finished with value: 0.07197031378746033 and parameters: {'n_estimators': 2500, 'learning_rate': 0.06399842367255495, 'max_depth': 8, 'subsample': 0.8071315044252536, 'colsample_bytree': 0.7266228356555355, 'min_child_weight': 5}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:11,830] Trial 19 finished with value: 0.06475953757762909 and parameters: {'n_estimators': 1500, 'learning_rate': 0.020376167281705763, 'max_depth': 6, 'subsample': 0.7483742370372961, 'colsample_bytree': 0.6408554886842408, 'min_child_weight': 7}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:16,049] Trial 20 finished with value: 0.0649176612496376 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00636710734174366, 'max_depth': 4, 'subsample': 0.6822880398395288, 'colsample_bytree': 0.7724092697314707, 'min_child_weight': 9}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:20,297] Trial 21 finished with value: 0.06491515040397644 and parameters: {'n_estimators': 1500, 'learning_rate': 0.010478801970688413, 'max_depth': 5, 'subsample': 0.6809348477365884, 'colsample_bytree': 0.8080550992694855, 'min_child_weight': 8}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:25,774] Trial 22 finished with value: 0.06137993559241295 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009674404920425036, 'max_depth': 5, 'subsample': 0.6934086553900508, 'colsample_bytree': 0.810367291055832, 'min_child_weight': 9}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:32,137] Trial 23 finished with value: 0.06635558605194092 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008898366874068897, 'max_depth': 6, 'subsample': 0.6186284481759408, 'colsample_bytree': 0.8499017747962022, 'min_child_weight': 9}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:37,452] Trial 24 finished with value: 0.07722675055265427 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012805279747753836, 'max_depth': 5, 'subsample': 0.6563712886210534, 'colsample_bytree': 0.7362082025870849, 'min_child_weight': 9}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:42,760] Trial 25 finished with value: 0.07009224593639374 and parameters: {'n_estimators': 2500, 'learning_rate': 0.0064113492140358865, 'max_depth': 4, 'subsample': 0.640626475420354, 'colsample_bytree': 0.8017848480477431, 'min_child_weight': 6}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:47,251] Trial 26 finished with value: 0.07538651674985886 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011463103319120914, 'max_depth': 6, 'subsample': 0.7087561391579843, 'colsample_bytree': 0.6918910719176715, 'min_child_weight': 10}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:50,325] Trial 27 finished with value: 0.060797594487667084 and parameters: {'n_estimators': 3000, 'learning_rate': 0.018392022168062714, 'max_depth': 5, 'subsample': 0.7491079283139305, 'colsample_bytree': 0.8343011909688376, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:53,403] Trial 28 finished with value: 0.059428419917821884 and parameters: {'n_estimators': 3000, 'learning_rate': 0.024815903553619272, 'max_depth': 5, 'subsample': 0.7569394306945045, 'colsample_bytree': 0.8366363567304664, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:55,449] Trial 29 finished with value: 0.05815701186656952 and parameters: {'n_estimators': 3000, 'learning_rate': 0.027804758486839255, 'max_depth': 4, 'subsample': 0.7770684564886877, 'colsample_bytree': 0.838907041535796, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:35:57,672] Trial 30 finished with value: 0.0576615072786808 and parameters: {'n_estimators': 3000, 'learning_rate': 0.0270908067457278, 'max_depth': 4, 'subsample': 0.7785134828712882, 'colsample_bytree': 0.7816625478369852, 'min_child_weight': 3}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:00,075] Trial 31 finished with value: 0.06230506673455238 and parameters: {'n_estimators': 3000, 'learning_rate': 0.025676278740390183, 'max_depth': 4, 'subsample': 0.7726996184898888, 'colsample_bytree': 0.8511609760368551, 'min_child_weight': 3}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:01,996] Trial 32 finished with value: 0.07526445388793945 and parameters: {'n_estimators': 3000, 'learning_rate': 0.03233661879556164, 'max_depth': 4, 'subsample': 0.8027960004956713, 'colsample_bytree': 0.7836273007065065, 'min_child_weight': 4}. Best is trial 2 with value: 0.0550946407020092.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

Best NDVI RMSE: 0.05509
NDVI Model saved to: saved_models/ndvi_proxy_model.pkl
Augmenting features with Predicted NDVI...
New Feature Shape: (714, 769)

## Auxilary task of predicting State

In [22]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# ==========================================
# PART 1.5: STATE CLASSIFICATION MODEL
# ==========================================
print("\n" + "="*40)
print(" STEP 1.5: STATE CLASSIFICATION MODEL")
print("="*40)

# 0. Prepare Data (Encode State Labels)
# We assume 'train_df' is available from your previous context
le_state = LabelEncoder()
y_state_encoded = le_state.fit_transform(state_raw)
num_classes = len(le_state.classes_)

print(f"Detecting {num_classes} States: {le_state.classes_}")

# 1. Split for State Optimization
X_st_train, X_st_val, y_st_train, y_st_val = train_test_split(
    X_raw, y_state_encoded, test_size=0.2, random_state=42, stratify=y_state_encoded
)

# 2. Define Objective (Accuracy/LogLoss)
def objective_state(trial):
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 2000, step=250),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'subsample': trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 7),
        # Classification specific params
        'objective': 'multi:softmax',  # Predicts class integer directly
        'num_class': num_classes,
        'eval_metric': 'mlogloss',     # Optimize for log loss
        'tree_method': 'hist', 'device': 'cuda', 'n_jobs': -1
    }
    
    # Internal split for early stopping
    tr_x, val_x, tr_y, val_y = train_test_split(X_st_train, y_st_train, test_size=0.2, stratify=y_st_train)
    
    model = xgb.XGBClassifier(**param)
    model.fit(tr_x, tr_y, eval_set=[(val_x, val_y)], early_stopping_rounds=50, verbose=False)
    
    # Return Accuracy (Maximized) or LogLoss (Minimized). Let's use LogLoss for stability.
    # Note: Optuna minimizes by default.
    preds = model.predict(val_x)
    accuracy = accuracy_score(val_y, preds)
    return 1 - accuracy # Minimize Error Rate

# 3. Run Optuna
study_state = optuna.create_study(direction="minimize", study_name="State_Classify")
study_state.optimize(objective_state, n_trials=40)
print(f"Best State Error Rate: {study_state.best_value:.5f}")

# 4. Train Final State Model & Save
best_state_params = study_state.best_params
best_state_params.update({
    'tree_method': 'hist', 'device': 'cuda', 'n_jobs': -1,
    'objective': 'multi:softmax', 'num_class': num_classes, 'eval_metric': 'mlogloss'
})

final_state_model = xgb.XGBClassifier(**best_state_params)
final_state_model.fit(X_raw, y_state_encoded)




# SAVE STATE MODEL & ENCODER
state_model_path = os.path.join(MODEL_DIR, "state_classifier_model.pkl")
encoder_path = os.path.join(MODEL_DIR, "state_encoder.pkl")

with open(state_model_path, "wb") as f:
    pickle.dump(final_state_model, f)
with open(encoder_path, "wb") as f:
    pickle.dump(le_state, f) # Save this to decode predictions later!

print(f"State Model saved to: {state_model_path}")

# 5. AUGMENT FEATURES (Add State to the Feature Set)
print("Augmenting features with Predicted State...")
state_preds = final_state_model.predict(X_raw)




# ==========================================
# REPLACEMENT FOR STEP 5: AUGMENT FEATURES
# ==========================================
from sklearn.preprocessing import OneHotEncoder

print("Augmenting features with Predicted State...")

# 1. Get the INTEGER predictions (0, 1, 2...)
state_preds_int = final_state_model.predict(X_raw)

# 2. Convert to ONE-HOT (Binary Columns)
# reshape(-1, 1) turns the list into a column vector
encoder = OneHotEncoder(sparse_output=False, categories='auto')
state_preds_onehot = encoder.fit_transform(state_preds_int.reshape(-1, 1))

# 3. Stack horizontally
# X_final will now grow by [Number of States] columns, not just 1.
if 'X_final' not in locals():
    X_final = X_raw

X_final = np.column_stack((X_final, state_preds_onehot))

print(f"Original Features: {X_raw.shape[1]}")
print(f"Added State Columns: {state_preds_onehot.shape[1]}")
print(f"Final Feature Shape: {X_final.shape}")
# Combine: X_final was (X_raw + NDVI). Now we add State.

========================================
 STEP 1.5: STATE CLASSIFICATION MODEL
========================================

[I 2025-12-17 06:36:32,081] A new study created in memory with name: State_Classify

Detecting 4 States: [0 1 2 3]

/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:35,138] Trial 0 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 1750, 'learning_rate': 0.04863455134498265, 'max_depth': 6, 'subsample': 0.6120618248138558, 'colsample_bytree': 0.8224819121560865, 'min_child_weight': 4}. Best is trial 0 with value: 0.09565217391304348.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:37,924] Trial 1 finished with value: 0.12173913043478257 and parameters: {'n_estimators': 1250, 'learning_rate': 0.046312703811483384, 'max_depth': 4, 'subsample': 0.8698504414129158, 'colsample_bytree': 0.8505899856570085, 'min_child_weight': 7}. Best is trial 0 with value: 0.09565217391304348.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:42,252] Trial 2 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 1000, 'learning_rate': 0.030463739408666066, 'max_depth': 8, 'subsample': 0.7103009469178487, 'colsample_bytree': 0.6645159401951952, 'min_child_weight': 7}. Best is trial 2 with value: 0.07826086956521738.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:48,138] Trial 3 finished with value: 0.060869565217391286 and parameters: {'n_estimators': 1750, 'learning_rate': 0.03103895254553196, 'max_depth': 7, 'subsample': 0.779254716452251, 'colsample_bytree': 0.6647176675417259, 'min_child_weight': 6}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:50,817] Trial 4 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 1250, 'learning_rate': 0.05421954648341491, 'max_depth': 3, 'subsample': 0.6873247686867728, 'colsample_bytree': 0.7951206002344927, 'min_child_weight': 6}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:55,854] Trial 5 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05007653794478407, 'max_depth': 8, 'subsample': 0.7452743765065324, 'colsample_bytree': 0.8297931089757341, 'min_child_weight': 3}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:36:59,701] Trial 6 finished with value: 0.06956521739130439 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03538977922039095, 'max_depth': 3, 'subsample': 0.7073958936713713, 'colsample_bytree': 0.7403041443781985, 'min_child_weight': 2}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:01,966] Trial 7 finished with value: 0.14782608695652177 and parameters: {'n_estimators': 1250, 'learning_rate': 0.06886456417949796, 'max_depth': 5, 'subsample': 0.8501376036572406, 'colsample_bytree': 0.8585796256589537, 'min_child_weight': 7}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:06,809] Trial 8 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 1250, 'learning_rate': 0.032013457832802565, 'max_depth': 6, 'subsample': 0.7321936417743291, 'colsample_bytree': 0.7658871152759232, 'min_child_weight': 2}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:11,700] Trial 9 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 2000, 'learning_rate': 0.027237439308508048, 'max_depth': 3, 'subsample': 0.8175081672928497, 'colsample_bytree': 0.7705751996522536, 'min_child_weight': 2}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:15,763] Trial 10 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 500, 'learning_rate': 0.011491809959579626, 'max_depth': 7, 'subsample': 0.7991461562971445, 'colsample_bytree': 0.600998074576271, 'min_child_weight': 5}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:16,893] Trial 11 finished with value: 0.06956521739130439 and parameters: {'n_estimators': 750, 'learning_rate': 0.1545008509007052, 'max_depth': 5, 'subsample': 0.6676364620441899, 'colsample_bytree': 0.7022250278837014, 'min_child_weight': 1}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:25,086] Trial 12 finished with value: 0.11304347826086958 and parameters: {'n_estimators': 1750, 'learning_rate': 0.0179552740482499, 'max_depth': 7, 'subsample': 0.7752065273888837, 'colsample_bytree': 0.7033260286529321, 'min_child_weight': 5}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:26,067] Trial 13 finished with value: 0.12173913043478257 and parameters: {'n_estimators': 1500, 'learning_rate': 0.09238613323400882, 'max_depth': 4, 'subsample': 0.651895772352107, 'colsample_bytree': 0.641724604757652, 'min_child_weight': 4}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:32,156] Trial 14 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 750, 'learning_rate': 0.017882861125768992, 'max_depth': 7, 'subsample': 0.7702458095617848, 'colsample_bytree': 0.7183254708913613, 'min_child_weight': 1}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:36,901] Trial 15 finished with value: 0.10434782608695647 and parameters: {'n_estimators': 1500, 'learning_rate': 0.021958180162721327, 'max_depth': 4, 'subsample': 0.8173872841923128, 'colsample_bytree': 0.6573028493772881, 'min_child_weight': 3}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:43,128] Trial 16 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011503799038050056, 'max_depth': 6, 'subsample': 0.7138648131545664, 'colsample_bytree': 0.891766081738508, 'min_child_weight': 5}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:45,062] Trial 17 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 1750, 'learning_rate': 0.08912253356576127, 'max_depth': 7, 'subsample': 0.6235903074398852, 'colsample_bytree': 0.7357961182773761, 'min_child_weight': 6}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:49,323] Trial 18 finished with value: 0.07826086956521738 and parameters: {'n_estimators': 1500, 'learning_rate': 0.034987875537235806, 'max_depth': 5, 'subsample': 0.7722790105409996, 'colsample_bytree': 0.6024641973424071, 'min_child_weight': 3}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:50,512] Trial 19 finished with value: 0.11304347826086958 and parameters: {'n_estimators': 1000, 'learning_rate': 0.18599221991468723, 'max_depth': 3, 'subsample': 0.6911025886671154, 'colsample_bytree': 0.680536144644332, 'min_child_weight': 2}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:54,992] Trial 20 finished with value: 0.08695652173913049 and parameters: {'n_estimators': 750, 'learning_rate': 0.02091352072491159, 'max_depth': 8, 'subsample': 0.846417550922138, 'colsample_bytree': 0.6299982880619895, 'min_child_weight': 6}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:55,860] Trial 21 finished with value: 0.15652173913043477 and parameters: {'n_estimators': 500, 'learning_rate': 0.17954584615253624, 'max_depth': 5, 'subsample': 0.6686365637361688, 'colsample_bytree': 0.707983460222574, 'min_child_weight': 1}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:37:57,243] Trial 22 finished with value: 0.11304347826086958 and parameters: {'n_estimators': 750, 'learning_rate': 0.13115928453492653, 'max_depth': 4, 'subsample': 0.6456233800939695, 'colsample_bytree': 0.6852626116587456, 'min_child_weight': 1}. Best is trial 3 with value: 0.060869565217391286.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:00,724] Trial 23 finished with value: 0.05217391304347829 and parameters: {'n_estimators': 750, 'learning_rate': 0.06813486394203569, 'max_depth': 5, 'subsample': 0.7302487193703906, 'colsample_bytree': 0.7409163852706608, 'min_child_weight': 2}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:02,595] Trial 24 finished with value: 0.10434782608695647 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06727085602268096, 'max_depth': 6, 'subsample': 0.7227832400218055, 'colsample_bytree': 0.7557286571023133, 'min_child_weight': 4}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:04,873] Trial 25 finished with value: 0.08695652173913049 and parameters: {'n_estimators': 500, 'learning_rate': 0.03671245601686984, 'max_depth': 3, 'subsample': 0.7557604655757376, 'colsample_bytree': 0.7367612757192566, 'min_child_weight': 2}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:07,024] Trial 26 finished with value: 0.10434782608695647 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07183428037492746, 'max_depth': 4, 'subsample': 0.7922672515567719, 'colsample_bytree': 0.7908083057007731, 'min_child_weight': 3}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:10,489] Trial 27 finished with value: 0.06956521739130439 and parameters: {'n_estimators': 750, 'learning_rate': 0.10634879394825629, 'max_depth': 7, 'subsample': 0.7448711370584045, 'colsample_bytree': 0.791079551851439, 'min_child_weight': 2}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:12,969] Trial 28 finished with value: 0.13043478260869568 and parameters: {'n_estimators': 1500, 'learning_rate': 0.04071245577729356, 'max_depth': 5, 'subsample': 0.887854660113363, 'colsample_bytree': 0.7361176563979307, 'min_child_weight': 3}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:17,978] Trial 29 finished with value: 0.09565217391304348 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02534220993280423, 'max_depth': 6, 'subsample': 0.6953116755696598, 'colsample_bytree': 0.8142231620348169, 'min_child_weight': 4}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:21,493] Trial 30 finished with value: 0.13043478260869568 and parameters: {'n_estimators': 1750, 'learning_rate': 0.057660628510428254, 'max_depth': 8, 'subsample': 0.8032000457008671, 'colsample_bytree': 0.6324220110133497, 'min_child_weight': 5}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:23,180] Trial 31 finished with value: 0.11304347826086958 and parameters: {'n_estimators': 750, 'learning_rate': 0.15124604001127445, 'max_depth': 5, 'subsample': 0.6789020644225309, 'colsample_bytree': 0.692189529283021, 'min_child_weight': 1}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:26,897] Trial 32 finished with value: 0.060869565217391286 and parameters: {'n_estimators': 750, 'learning_rate': 0.04388575436760263, 'max_depth': 4, 'subsample': 0.6007656053805183, 'colsample_bytree': 0.7206478504773183, 'min_child_weight': 1}. Best is trial 23 with value: 0.05217391304347829.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
[I 2025-12-17 06:38:30,564] Trial 33 finished with value: 0.034782608695652195 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04341841426030947, 'max_depth': 4, 'subsample': 0.6025761634041263, 'colsample_bytree': 0.7210088018587792, 'min_child_weight': 2}. Best is trial 33 with value: 0.034782608695652195.
/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

Best State Error Rate: 0.03478
State Model saved to: saved_models/state_classifier_model.pkl
Augmenting features with Predicted State...
Augmenting features with Predicted State...
Original Features: 768
Added State Columns: 4
Final Feature Shape: (714, 773)

In [23]:
# # ==========================================
# # PART 2: BIOMASS MODELS (With Constraints)
# # ==========================================
# print("\n" + "="*40)
# print(" STEP 2: BIOMASS MODELS")
# print("="*40)

# # 1. Setup Data for Biomass
# # We use 'groups_raw' (dates) for GroupKFold to prevent leakage
# X_bio_tuning, X_bio_test, y_bio_tuning, y_bio_test, g_bio_tuning, g_bio_test = train_test_split(
#     X_final, y_raw, groups_raw, test_size=0.2, random_state=42
# )

# target_cols = ['Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g']

# # 2. Define Objective (With Logic for Constraints)
# def objective_biomass(trial, target_name, X, y, groups):
    
#     # Setup Monotonic Constraint if target is Dry_Dead_g
#     # 0 = No constraint, -1 = Negative constraint
#     constraint_tuple = None
#     if target_name == 'Dry_Dead_g':
#         # Apply constraint ONLY to the last column (Predicted NDVI)
#         n_feats = X.shape[1]
#         c_list = [0] * (n_feats - 1) + [-1]
#         constraint_tuple = tuple(c_list)

#     param = {
#         'n_estimators': trial.suggest_int('n_estimators', 500, 3000, step=500),
#         'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1, log=True),
#         'max_depth': trial.suggest_int('max_depth', 3, 10),
#         'subsample': trial.suggest_float('subsample', 0.6, 0.95),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.95),
#         'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
#         'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
#         'tree_method': 'hist', 'device': 'cuda', 'n_jobs': -1,
#         # INJECT CONSTRAINT
#         'monotone_constraints': constraint_tuple 
#     }

#     scores = []
   
#     scores_weighted=[]
#     gkf = GroupKFold(n_splits=4)
#     for train_idx, val_idx in gkf.split(X, y, groups=groups):
#         X_tr, X_val = X[train_idx], X[val_idx]
#         y_tr, y_val = y[train_idx], y[val_idx]

#         model = xgb.XGBRegressor(**param)
#         model.fit(X_tr, y_tr)
        
#         # Prediction & Clipping (Non-negative)
#         preds = np.maximum(0, model.predict(X_val))
#         scores.append(r2_score(y_val, preds))
        
       
   

   

#     return np.mean(scores)

# # 3. Loop over targets
# best_params_dict = {}

# for i, target in enumerate(target_cols):
#     print(f"\nOptimizing {target}...")
    
#     # Create Study
#     study = optuna.create_study(directions=["maximize"], study_name=f"XGB_{target}")
#     func = partial(objective_biomass, target_name=target, 
#                    X=X_bio_tuning, y=y_bio_tuning[:, i], groups=g_bio_tuning)
#     study.optimize(func, n_trials=20)
    
#     print(f"Best R2 for {target}: {study.best_value:.4f}")
#     best_params_dict[target] = study.best_params
    
#     # Train Final Model (On all tuning data)
#     print(f"Training Final Model for {target}...")
    
#     # Re-create constraint tuple for final training
#     constraint_tuple = None
#     if target == 'Dry_Dead_g':
#         c_list = [0] * (X_bio_tuning.shape[1] - 1) + [-1]
#         constraint_tuple = tuple(c_list)

#     final_model = xgb.XGBRegressor(
#         **study.best_params,
#         tree_method='hist', device='cuda', n_jobs=-1,
#         monotone_constraints=constraint_tuple
#     )
    
#     final_model.fit(X_bio_tuning, y_bio_tuning[:, i])
    
#     # Save Biomass Model
#     save_path = os.path.join(MODEL_DIR, f"xgb_{target}.pkl")
#     with open(save_path, "wb") as f:
#         pickle.dump(final_model, f)
#     print(f"Saved -> {save_path}")

# # Save all params to JSON
# with open(os.path.join(MODEL_DIR, "best_params.json"), "w") as f:
#     json.dump(best_params_dict, f, indent=4)

# print("\nAll models trained and saved successfully.")

In [24]:
import numpy as np
import xgboost as xgb
import pickle
import os
import json
from sklearn.model_selection import GroupKFold, train_test_split, KFold
from sklearn.metrics import r2_score
from functools import partial
import optuna

# ==========================================
# PART 2: STATE-SPECIFIC BIOMASS MODELS
# ==========================================
print("\n" + "="*40)
print(" STEP 2: STATE-SPECIFIC BIOMASS MODELS")
print("="*40)

# ------------------------------------------
# 1. SETUP & CONFIGURATION
# ------------------------------------------
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)

# --- CRITICAL FIX: Don't use le_state ---
# Calculate number of classes directly from the data (e.g. 0, 1, 2, 3)
unique_state_indices = np.unique(y_state_encoded)
num_state_classes = len(unique_state_indices) 
# OR hardcode if you are certain: num_state_classes = 4

print(f"Detected {num_state_classes} Unique States: {unique_state_indices}")
print("Feature Structure Assumption: [ DINO_FEATS | NDVI | STATE_OHE ]")

target_cols = ['Dry_Clover_g', 'Dry_Dead_g', 'Dry_Green_g']
best_params_dict = {}

# ------------------------------------------
# 2. DEFINE OBJECTIVE FUNCTION
# ------------------------------------------
def objective_biomass(trial, target_name, X, y, groups, n_state_cols):
    
    # --- DYNAMIC CONSTRAINT LOGIC ---
    constraint_tuple = None
    
    if target_name == 'Dry_Dead_g':
        n_feats = X.shape[1]
        
        # Calculate NDVI index relative to the end
        # Example: Total (1541) - States (4) - 1 = Index 1536 (NDVI)
        ndvi_idx = n_feats - n_state_cols - 1
        
        # Safety Check
        if ndvi_idx < 0:
            raise ValueError("Feature matrix is too small to contain NDVI + State OHE!")
            
        # Create Constraint List (0 everywhere, -1 at NDVI index)
        c_list = [0] * n_feats
        c_list[ndvi_idx] = -1 
        
        constraint_tuple = tuple(c_list)

    # --- HYPERPARAMETERS ---
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 2000, step=100),
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.15, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'subsample': trial.suggest_float('subsample', 0.5, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 0.9),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
        'tree_method': 'hist', 
        'device': 'cuda', 
        'n_jobs': -1,
        'monotone_constraints': constraint_tuple 
    }

    scores = []
    
    # --- CROSS VALIDATION STRATEGY ---
    n_groups = len(np.unique(groups))
    
    if n_groups >= 4:
        gkf = GroupKFold(n_splits=4)
    else:
        n_splits = min(n_groups, 3) if n_groups > 1 else 2
        gkf = KFold(n_splits=n_splits)

    try:
        for train_idx, val_idx in gkf.split(X, y, groups=groups):
            X_tr, X_val = X[train_idx], X[val_idx]
            y_tr, y_val = y[train_idx], y[val_idx]

            model = xgb.XGBRegressor(**param)
            model.fit(X_tr, y_tr, verbose=False)
            
            # Predict & Clip
            preds = np.maximum(0, model.predict(X_val))
            scores.append(r2_score(y_val, preds))
            
        return np.mean(scores)
        
    except Exception as e:
        print(f"Trial failed: {e}")
        return -999

# ------------------------------------------
# 3. MAIN TRAINING LOOP (By State -> By Target)
# ------------------------------------------

for state_idx in unique_state_indices:
    
    # --- ALIAS LOGIC ---
    # We name the model 'state_0', 'state_1', etc. 
    # This aligns with your inference logic later.
    state_str = f'state_{state_idx}'
    
    print(f"\n" + "-"*30)
    print(f" PROCESSING STATE: {state_idx} ({state_str})")
    print("-"*30)
    
    # Filter Data
    state_mask = (y_state_encoded == state_idx)
    
    X_state = X_final[state_mask]
    y_state = y_raw[state_mask]
    groups_state = groups_raw[state_mask]
    
    print(f"Samples: {X_state.shape[0]}")

    # Split
    X_tune, X_hold, y_tune, y_hold, g_tune, g_hold = train_test_split(
        X_state, y_state, groups_state, test_size=0.15, random_state=42
    )

    for i, target in enumerate(target_cols):
        model_id = f"{state_str}_{target}" # e.g. state_0_Dry_Clover_g
        
        print(f"Optimizing {model_id}...")
        
        # Optimize
        study = optuna.create_study(directions=["maximize"], study_name=f"XGB_{model_id}")
        func = partial(objective_biomass, target_name=target, 
                       X=X_tune, y=y_tune[:, i], groups=g_tune, 
                       n_state_cols=num_state_classes) 
        
        study.optimize(func, n_trials=25) # Increased from 1 for actual training
        best_params_dict[model_id] = study.best_params
        
        print(f"Best R2: {study.best_value:.4f}")
        
        # Train Final Model
        final_constraint = None
        if target == 'Dry_Dead_g':
            n_feats = X_state.shape[1]
            ndvi_idx = n_feats - num_state_classes - 1
            c_list = [0] * n_feats
            c_list[ndvi_idx] = -1
            final_constraint = tuple(c_list)

        final_model = xgb.XGBRegressor(
            **study.best_params,
            tree_method='hist', device='cuda', n_jobs=-1,
            monotone_constraints=final_constraint
        )
        
        final_model.fit(X_state, y_state[:, i])
        
        # Save
        # e.g. "xgb_state_0_Dry_Clover_g.pkl"
        save_name = f"xgb_{model_id}.pkl" 
        save_path = os.path.join(MODEL_DIR, save_name)
        with open(save_path, "wb") as f:
            pickle.dump(final_model, f)
        print(f"Saved -> {save_name}")

# ------------------------------------------
# 4. SAVE METADATA
# ------------------------------------------
with open(os.path.join(MODEL_DIR, "best_params_per_state.json"), "w") as f:
    json.dump(best_params_dict, f, indent=4)

print("\nAll state-specific models trained and saved successfully.")

========================================
 STEP 2: STATE-SPECIFIC BIOMASS MODELS
========================================
Detected 4 Unique States: [0 1 2 3]
Feature Structure Assumption: [ DINO_FEATS | NDVI | STATE_OHE ]

------------------------------
 PROCESSING STATE: 0 (state_0)
------------------------------

[I 2025-12-17 06:38:50,768] A new study created in memory with name: XGB_state_0_Dry_Clover_g

Samples: 150
Optimizing state_0_Dry_Clover_g...

[I 2025-12-17 06:38:57,168] Trial 0 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1500, 'learning_rate': 0.005074179833562416, 'max_depth': 5, 'subsample': 0.5438132616365217, 'colsample_bytree': 0.7349312130509197, 'reg_alpha': 0.00019295892732046325, 'reg_lambda': 0.6300454849795082}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:01,089] Trial 1 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1500, 'learning_rate': 0.00525326373674749, 'max_depth': 4, 'subsample': 0.6569106785710312, 'colsample_bytree': 0.7762433982742745, 'reg_alpha': 8.270680159113956, 'reg_lambda': 0.2809166553830558}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:05,946] Trial 2 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1100, 'learning_rate': 0.005776908282600414, 'max_depth': 8, 'subsample': 0.7790687132582533, 'colsample_bytree': 0.6568132591748632, 'reg_alpha': 0.4225660712734291, 'reg_lambda': 0.0008060181530621517}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:11,792] Trial 3 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1900, 'learning_rate': 0.06819421636183262, 'max_depth': 3, 'subsample': 0.6012979929442364, 'colsample_bytree': 0.7639260907589209, 'reg_alpha': 0.004029934886538551, 'reg_lambda': 7.622272873860411}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:13,661] Trial 4 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 700, 'learning_rate': 0.03077989848932237, 'max_depth': 6, 'subsample': 0.5007158825783097, 'colsample_bytree': 0.6287788055074779, 'reg_alpha': 6.6681861867767696, 'reg_lambda': 0.0004424666936680616}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:14,958] Trial 5 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 300, 'learning_rate': 0.07435154295713726, 'max_depth': 5, 'subsample': 0.6505172991143618, 'colsample_bytree': 0.7166418491820183, 'reg_alpha': 0.0003322775291699581, 'reg_lambda': 0.0014313995736493954}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:19,575] Trial 6 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1900, 'learning_rate': 0.1018616372639932, 'max_depth': 4, 'subsample': 0.7755087226893947, 'colsample_bytree': 0.8716800132284588, 'reg_alpha': 0.032826271136981895, 'reg_lambda': 0.005545110352355418}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:25,446] Trial 7 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1400, 'learning_rate': 0.01869297522883354, 'max_depth': 5, 'subsample': 0.5850584265727993, 'colsample_bytree': 0.7138223934020871, 'reg_alpha': 0.006958716752719114, 'reg_lambda': 0.0528973545738946}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:39,716] Trial 8 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1800, 'learning_rate': 0.0053881954271883335, 'max_depth': 9, 'subsample': 0.5373005146677067, 'colsample_bytree': 0.5992643877311425, 'reg_alpha': 0.0002283627670590981, 'reg_lambda': 0.00042081835187730886}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:42,728] Trial 9 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1100, 'learning_rate': 0.001841633884960516, 'max_depth': 8, 'subsample': 0.8585225861392083, 'colsample_bytree': 0.620693336966523, 'reg_alpha': 7.5231021171756565, 'reg_lambda': 1.3465677737338608}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:45,958] Trial 10 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 700, 'learning_rate': 0.0016697897165328596, 'max_depth': 7, 'subsample': 0.7307171788688307, 'colsample_bytree': 0.5340188173349997, 'reg_alpha': 0.0014654830990034231, 'reg_lambda': 0.05778156852741705}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:50,892] Trial 11 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1500, 'learning_rate': 0.005795227078028348, 'max_depth': 3, 'subsample': 0.6671087118129393, 'colsample_bytree': 0.808203261579278, 'reg_alpha': 0.1798489029217583, 'reg_lambda': 0.5274103433512537}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:39:56,781] Trial 12 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1500, 'learning_rate': 0.0036106557541501698, 'max_depth': 5, 'subsample': 0.5959934756738763, 'colsample_bytree': 0.7979287823575795, 'reg_alpha': 0.6590137063854686, 'reg_lambda': 0.46152416945477354}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:02,068] Trial 13 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1300, 'learning_rate': 0.012065386714314941, 'max_depth': 4, 'subsample': 0.697543130268647, 'colsample_bytree': 0.8469694005357203, 'reg_alpha': 0.05315654217756744, 'reg_lambda': 0.1629163547851844}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:08,197] Trial 14 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1700, 'learning_rate': 0.011998248765141536, 'max_depth': 6, 'subsample': 0.5379829289004818, 'colsample_bytree': 0.7583576777478, 'reg_alpha': 1.8079094759537098, 'reg_lambda': 4.579691292303361}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:11,858] Trial 15 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 900, 'learning_rate': 0.002903200302973195, 'max_depth': 4, 'subsample': 0.6360838650789659, 'colsample_bytree': 0.8941877051679971, 'reg_alpha': 0.0010686420394422603, 'reg_lambda': 0.0116489273004419}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:16,884] Trial 16 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1600, 'learning_rate': 0.0010435369705622628, 'max_depth': 5, 'subsample': 0.878870264070222, 'colsample_bytree': 0.6884996736441157, 'reg_alpha': 0.00011369904616542475, 'reg_lambda': 1.3700690576956143}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:21,932] Trial 17 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1300, 'learning_rate': 0.023940408009855918, 'max_depth': 6, 'subsample': 0.7308817071651597, 'colsample_bytree': 0.7552305291446005, 'reg_alpha': 0.011141608200581512, 'reg_lambda': 0.1974106710424436}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:28,767] Trial 18 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00793518207257511, 'max_depth': 3, 'subsample': 0.556834704044404, 'colsample_bytree': 0.8037575753882418, 'reg_alpha': 0.08828523250911172, 'reg_lambda': 0.01558022619529596}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:34,060] Trial 19 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1700, 'learning_rate': 0.0032422302664263524, 'max_depth': 4, 'subsample': 0.8158536156177277, 'colsample_bytree': 0.8371385049819698, 'reg_alpha': 1.3228839427286168, 'reg_lambda': 1.652264827632379}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:39,202] Trial 20 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 900, 'learning_rate': 0.009099828110022481, 'max_depth': 7, 'subsample': 0.5037349987322315, 'colsample_bytree': 0.5698365396246475, 'reg_alpha': 0.001103070379351347, 'reg_lambda': 0.1046647467328245}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:44,175] Trial 21 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1100, 'learning_rate': 0.005096106149677585, 'max_depth': 9, 'subsample': 0.7909636826243392, 'colsample_bytree': 0.6790274272043049, 'reg_alpha': 0.38048220238605435, 'reg_lambda': 0.00012796678482095773}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:47,825] Trial 22 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1200, 'learning_rate': 0.0024699152931888712, 'max_depth': 7, 'subsample': 0.74282672980887, 'colsample_bytree': 0.6659613021069191, 'reg_alpha': 2.5021734285595993, 'reg_lambda': 0.0031599069129206957}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:40:52,630] Trial 23 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007733782364605546, 'max_depth': 8, 'subsample': 0.6913179205872215, 'colsample_bytree': 0.734957969873356, 'reg_alpha': 0.2233437191453723, 'reg_lambda': 0.46317842651336805}. Best is trial 0 with value: -0.020000030604635177.
[I 2025-12-17 06:41:00,268] Trial 24 finished with value: -0.020000030604635177 and parameters: {'n_estimators': 1400, 'learning_rate': 0.00477490058649721, 'max_depth': 8, 'subsample': 0.8334584022658239, 'colsample_bytree': 0.6485805748259573, 'reg_alpha': 0.01753703570727958, 'reg_lambda': 0.03219846271947031}. Best is trial 0 with value: -0.020000030604635177.

Best R2: -0.0200

[I 2025-12-17 06:41:02,441] A new study created in memory with name: XGB_state_0_Dry_Dead_g

Saved -> xgb_state_0_Dry_Clover_g.pkl
Optimizing state_0_Dry_Dead_g...

[I 2025-12-17 06:41:06,284] Trial 0 finished with value: -1.0835132249620534 and parameters: {'n_estimators': 900, 'learning_rate': 0.0011370375960151205, 'max_depth': 3, 'subsample': 0.6083213035585978, 'colsample_bytree': 0.8790573525936729, 'reg_alpha': 0.017499531916738625, 'reg_lambda': 0.6554636024623416}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:11,480] Trial 1 finished with value: -2.383265111172189 and parameters: {'n_estimators': 1600, 'learning_rate': 0.10526526672509069, 'max_depth': 5, 'subsample': 0.7648040973445844, 'colsample_bytree': 0.8096529996181132, 'reg_alpha': 1.8673740937219236, 'reg_lambda': 0.0056865122759313476}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:15,440] Trial 2 finished with value: -2.1666363197002165 and parameters: {'n_estimators': 1400, 'learning_rate': 0.09377922628553255, 'max_depth': 3, 'subsample': 0.7036892484778031, 'colsample_bytree': 0.538279875834836, 'reg_alpha': 0.052144742553437776, 'reg_lambda': 0.7943027377738547}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:21,872] Trial 3 finished with value: -2.630630866557378 and parameters: {'n_estimators': 1800, 'learning_rate': 0.07861313665990301, 'max_depth': 5, 'subsample': 0.6489405629481794, 'colsample_bytree': 0.721338273945108, 'reg_alpha': 0.15626383633702365, 'reg_lambda': 0.0015835847288553544}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:30,336] Trial 4 finished with value: -2.0490225432919456 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0021759606361299506, 'max_depth': 3, 'subsample': 0.5635681252637593, 'colsample_bytree': 0.8249134230403343, 'reg_alpha': 0.01379314643689309, 'reg_lambda': 0.11446317375774376}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:33,612] Trial 5 finished with value: -1.2260014722568895 and parameters: {'n_estimators': 400, 'learning_rate': 0.005074239926798214, 'max_depth': 8, 'subsample': 0.7353295358915026, 'colsample_bytree': 0.5891397732582879, 'reg_alpha': 0.011862363054809045, 'reg_lambda': 2.164318478639434}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:41:39,245] Trial 6 finished with value: -2.142602551978704 and parameters: {'n_estimators': 800, 'learning_rate': 0.00838153847768493, 'max_depth': 5, 'subsample': 0.7870343209378889, 'colsample_bytree': 0.6160741704750222, 'reg_alpha': 0.00012218321452816064, 'reg_lambda': 0.10656948399745417}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:42:01,060] Trial 7 finished with value: -2.491203794583365 and parameters: {'n_estimators': 1400, 'learning_rate': 0.008006976624015947, 'max_depth': 9, 'subsample': 0.6743541887579962, 'colsample_bytree': 0.5815708782980423, 'reg_alpha': 0.005282459885757937, 'reg_lambda': 0.00024798554660624555}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:42:12,974] Trial 8 finished with value: -2.4818914458681616 and parameters: {'n_estimators': 2000, 'learning_rate': 0.022913098093953855, 'max_depth': 6, 'subsample': 0.5615219067831784, 'colsample_bytree': 0.6509905497139581, 'reg_alpha': 0.00027852675578051014, 'reg_lambda': 0.00109807102219962}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:42:24,072] Trial 9 finished with value: -2.4237384106017896 and parameters: {'n_estimators': 1800, 'learning_rate': 0.0286081483574798, 'max_depth': 8, 'subsample': 0.8126323630696789, 'colsample_bytree': 0.5254314164341373, 'reg_alpha': 0.00042906715025980394, 'reg_lambda': 0.0011217036566462215}. Best is trial 0 with value: -1.0835132249620534.
[I 2025-12-17 06:42:28,139] Trial 10 finished with value: -0.8454454107217051 and parameters: {'n_estimators': 900, 'learning_rate': 0.001078981572169989, 'max_depth': 3, 'subsample': 0.8783623069631485, 'colsample_bytree': 0.8781102397766912, 'reg_alpha': 7.919133928587855, 'reg_lambda': 6.791995819856182}. Best is trial 10 with value: -0.8454454107217051.
[I 2025-12-17 06:42:32,223] Trial 11 finished with value: -0.8108494565771758 and parameters: {'n_estimators': 900, 'learning_rate': 0.001095690798032183, 'max_depth': 3, 'subsample': 0.8916552350261898, 'colsample_bytree': 0.8975567443519777, 'reg_alpha': 4.589056600590194, 'reg_lambda': 9.53289246323826}. Best is trial 11 with value: -0.8108494565771758.
[I 2025-12-17 06:42:37,811] Trial 12 finished with value: -0.7226014448215143 and parameters: {'n_estimators': 900, 'learning_rate': 0.001121094510305774, 'max_depth': 4, 'subsample': 0.8860576935797962, 'colsample_bytree': 0.8989114850897096, 'reg_alpha': 8.949670451380792, 'reg_lambda': 9.567141754568572}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:42:40,745] Trial 13 finished with value: -0.888316060885413 and parameters: {'n_estimators': 500, 'learning_rate': 0.0028680878178971984, 'max_depth': 4, 'subsample': 0.890757480960387, 'colsample_bytree': 0.7595627417768905, 'reg_alpha': 0.7557401162424795, 'reg_lambda': 7.008756545131887}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:42:47,337] Trial 14 finished with value: -1.5234564325522206 and parameters: {'n_estimators': 1100, 'learning_rate': 0.002358628011252328, 'max_depth': 4, 'subsample': 0.843649781589859, 'colsample_bytree': 0.8903703528469733, 'reg_alpha': 7.84412925493642, 'reg_lambda': 0.2393747942744993}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:42:50,900] Trial 15 finished with value: -1.84920966298553 and parameters: {'n_estimators': 600, 'learning_rate': 0.004065738380326441, 'max_depth': 4, 'subsample': 0.8490151150712647, 'colsample_bytree': 0.8139619104406571, 'reg_alpha': 0.895313135227697, 'reg_lambda': 0.03098720331313217}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:01,059] Trial 16 finished with value: -1.258232799198152 and parameters: {'n_estimators': 1200, 'learning_rate': 0.0014616759066357716, 'max_depth': 6, 'subsample': 0.8986765851245201, 'colsample_bytree': 0.7835584893081965, 'reg_alpha': 0.26267696112456335, 'reg_lambda': 1.7538788461383306}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:05,042] Trial 17 finished with value: -1.1108858111627242 and parameters: {'n_estimators': 700, 'learning_rate': 0.01749905621153392, 'max_depth': 4, 'subsample': 0.5125534491389306, 'colsample_bytree': 0.6896158005261517, 'reg_alpha': 2.9070536812437955, 'reg_lambda': 9.667728249259891}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:18,545] Trial 18 finished with value: -1.714114030898661 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0017376941759408376, 'max_depth': 7, 'subsample': 0.8249237881157978, 'colsample_bytree': 0.8532027048867473, 'reg_alpha': 0.0022995657649878907, 'reg_lambda': 0.018046442677253513}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:20,682] Trial 19 finished with value: -1.1403383606753397 and parameters: {'n_estimators': 300, 'learning_rate': 0.004412383695283753, 'max_depth': 5, 'subsample': 0.7584292930747978, 'colsample_bytree': 0.7491511483677508, 'reg_alpha': 0.19948660675965374, 'reg_lambda': 1.7522209463495546}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:25,324] Trial 20 finished with value: -1.7475980595693552 and parameters: {'n_estimators': 1300, 'learning_rate': 0.04664687373838463, 'max_depth': 4, 'subsample': 0.8157231909867974, 'colsample_bytree': 0.8477890094943072, 'reg_alpha': 2.386051562966788, 'reg_lambda': 0.5913715659627717}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:29,365] Trial 21 finished with value: -0.9043700432058708 and parameters: {'n_estimators': 900, 'learning_rate': 0.0010027271065954646, 'max_depth': 3, 'subsample': 0.8661734626226767, 'colsample_bytree': 0.8995120596942673, 'reg_alpha': 7.532722871893679, 'reg_lambda': 4.575593382824653}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:33,821] Trial 22 finished with value: -0.818087157844316 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0010602575001558198, 'max_depth': 3, 'subsample': 0.8731492147722075, 'colsample_bytree': 0.8600852385837302, 'reg_alpha': 9.710191324204214, 'reg_lambda': 9.617421191208177}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:38,204] Trial 23 finished with value: -1.3853559381993514 and parameters: {'n_estimators': 1000, 'learning_rate': 0.003040854896244694, 'max_depth': 3, 'subsample': 0.8964378396640559, 'colsample_bytree': 0.8488367766730851, 'reg_alpha': 1.207313736744161, 'reg_lambda': 2.465461916077465}. Best is trial 12 with value: -0.7226014448215143.
[I 2025-12-17 06:43:42,284] Trial 24 finished with value: -1.1925411627025388 and parameters: {'n_estimators': 700, 'learning_rate': 0.0015779317645825586, 'max_depth': 4, 'subsample': 0.8466431358058549, 'colsample_bytree': 0.7846449738436507, 'reg_alpha': 4.108615083777674, 'reg_lambda': 0.28578543523200417}. Best is trial 12 with value: -0.7226014448215143.

Best R2: -0.7226

[I 2025-12-17 06:43:43,853] A new study created in memory with name: XGB_state_0_Dry_Green_g

Saved -> xgb_state_0_Dry_Dead_g.pkl
Optimizing state_0_Dry_Green_g...

[I 2025-12-17 06:43:53,289] Trial 0 finished with value: 0.21795445276243045 and parameters: {'n_estimators': 1700, 'learning_rate': 0.001041502154259419, 'max_depth': 4, 'subsample': 0.7223914839905687, 'colsample_bytree': 0.8726466109207462, 'reg_alpha': 0.0016710238043361044, 'reg_lambda': 0.006412689986038972}. Best is trial 0 with value: 0.21795445276243045.
[I 2025-12-17 06:43:57,605] Trial 1 finished with value: 0.2102687360417936 and parameters: {'n_estimators': 300, 'learning_rate': 0.007480095288047319, 'max_depth': 9, 'subsample': 0.8697232527854294, 'colsample_bytree': 0.5940036675278877, 'reg_alpha': 0.0010558855192158059, 'reg_lambda': 0.019546694695493496}. Best is trial 0 with value: 0.21795445276243045.
[I 2025-12-17 06:44:04,868] Trial 2 finished with value: 0.17608952376299492 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0011918663608142491, 'max_depth': 5, 'subsample': 0.6004099571776002, 'colsample_bytree': 0.8365487308245153, 'reg_alpha': 1.9313137708331956, 'reg_lambda': 0.0020756441871904348}. Best is trial 0 with value: 0.21795445276243045.
[I 2025-12-17 06:44:11,525] Trial 3 finished with value: 0.30182129382940404 and parameters: {'n_estimators': 1200, 'learning_rate': 0.014119953091272579, 'max_depth': 4, 'subsample': 0.508366833115112, 'colsample_bytree': 0.8450199132470576, 'reg_alpha': 0.00049237706067902, 'reg_lambda': 0.004315949016262028}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:18,445] Trial 4 finished with value: 0.2659551567884497 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007214277635352741, 'max_depth': 5, 'subsample': 0.6204036092536858, 'colsample_bytree': 0.7584616826120487, 'reg_alpha': 0.031260453483878244, 'reg_lambda': 0.10727553911981838}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:23,634] Trial 5 finished with value: 0.25202309946886564 and parameters: {'n_estimators': 700, 'learning_rate': 0.004651629937003241, 'max_depth': 5, 'subsample': 0.7105852152239018, 'colsample_bytree': 0.7383497018141818, 'reg_alpha': 0.14631481164120091, 'reg_lambda': 0.00028262787413377966}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:35,356] Trial 6 finished with value: 0.26791975939957646 and parameters: {'n_estimators': 1600, 'learning_rate': 0.0028814443134169195, 'max_depth': 6, 'subsample': 0.7904637286094949, 'colsample_bytree': 0.5938125676517623, 'reg_alpha': 4.944334959171701, 'reg_lambda': 2.53033027548143}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:39,605] Trial 7 finished with value: 0.17856106335495522 and parameters: {'n_estimators': 400, 'learning_rate': 0.007697896480662809, 'max_depth': 6, 'subsample': 0.7637182544179568, 'colsample_bytree': 0.8473537558392659, 'reg_alpha': 0.00019037033518359668, 'reg_lambda': 0.0001719046260284339}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:48,944] Trial 8 finished with value: 0.15008844586115533 and parameters: {'n_estimators': 1900, 'learning_rate': 0.03117213829033528, 'max_depth': 7, 'subsample': 0.8327114220603502, 'colsample_bytree': 0.7292545485258929, 'reg_alpha': 0.023439039693986443, 'reg_lambda': 0.01274710539149776}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:56,095] Trial 9 finished with value: 0.30133092623638724 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0311615884900969, 'max_depth': 8, 'subsample': 0.8303577006527822, 'colsample_bytree': 0.5137523696588626, 'reg_alpha': 1.465607253836894, 'reg_lambda': 0.00045112363296192034}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:44:59,754] Trial 10 finished with value: 0.2485437144342622 and parameters: {'n_estimators': 1300, 'learning_rate': 0.11225538445070131, 'max_depth': 3, 'subsample': 0.5078989755801293, 'colsample_bytree': 0.8969892456521138, 'reg_alpha': 0.002704447289939627, 'reg_lambda': 0.33823862173968194}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:07,918] Trial 11 finished with value: 0.2807613008349161 and parameters: {'n_estimators': 1300, 'learning_rate': 0.027483931953287164, 'max_depth': 9, 'subsample': 0.6237100807911218, 'colsample_bytree': 0.5004671149986182, 'reg_alpha': 0.3694202224300802, 'reg_lambda': 0.0013676113280959089}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:20,054] Trial 12 finished with value: 0.2750699032548476 and parameters: {'n_estimators': 1500, 'learning_rate': 0.024826749048539324, 'max_depth': 8, 'subsample': 0.5097319455030438, 'colsample_bytree': 0.6449849213854956, 'reg_alpha': 0.00013560388890417, 'reg_lambda': 0.0009069631873315913}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:22,265] Trial 13 finished with value: 0.29633847450226614 and parameters: {'n_estimators': 800, 'learning_rate': 0.0779247528816021, 'max_depth': 3, 'subsample': 0.8996097787467325, 'colsample_bytree': 0.5060749282583727, 'reg_alpha': 0.6129301020836055, 'reg_lambda': 0.00015269382395430284}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:36,709] Trial 14 finished with value: 0.2168008996044328 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017372205627307173, 'max_depth': 7, 'subsample': 0.5740555550955864, 'colsample_bytree': 0.7944005512611659, 'reg_alpha': 0.007507681972408857, 'reg_lambda': 0.003623543488028668}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:42,733] Trial 15 finished with value: 0.23590420367029588 and parameters: {'n_estimators': 1300, 'learning_rate': 0.0537137888303842, 'max_depth': 8, 'subsample': 0.6717856937895998, 'colsample_bytree': 0.6666805900349416, 'reg_alpha': 0.14180989898992252, 'reg_lambda': 0.09019180516481666}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:46,200] Trial 16 finished with value: 0.27623372201984425 and parameters: {'n_estimators': 1100, 'learning_rate': 0.05013447644861534, 'max_depth': 4, 'subsample': 0.8013580995800416, 'colsample_bytree': 0.5729780412231904, 'reg_alpha': 8.432300857562437, 'reg_lambda': 0.0007167641977335427}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:45:52,119] Trial 17 finished with value: 0.22526365393102357 and parameters: {'n_estimators': 700, 'learning_rate': 0.013220132618246389, 'max_depth': 7, 'subsample': 0.6701051112067122, 'colsample_bytree': 0.8041313554267651, 'reg_alpha': 0.00048445674252176757, 'reg_lambda': 3.2977592068453836}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:46:00,118] Trial 18 finished with value: 0.29102257929583475 and parameters: {'n_estimators': 1800, 'learning_rate': 0.01626670934063994, 'max_depth': 4, 'subsample': 0.5504579896482602, 'colsample_bytree': 0.6687318336401563, 'reg_alpha': 1.542675577121506, 'reg_lambda': 0.05065488541497184}. Best is trial 3 with value: 0.30182129382940404.
[I 2025-12-17 06:46:05,550] Trial 19 finished with value: 0.3293677396367205 and parameters: {'n_estimators': 1500, 'learning_rate': 0.14761567232219472, 'max_depth': 8, 'subsample': 0.7478555994792883, 'colsample_bytree': 0.5621909246919772, 'reg_alpha': 0.007380170614178059, 'reg_lambda': 0.0004411455389614186}. Best is trial 19 with value: 0.3293677396367205.
[I 2025-12-17 06:46:20,012] Trial 20 finished with value: 0.2649274834902499 and parameters: {'n_estimators': 1600, 'learning_rate': 0.0023519432371021773, 'max_depth': 6, 'subsample': 0.7396425714501741, 'colsample_bytree': 0.561044671499467, 'reg_alpha': 0.005511757347456836, 'reg_lambda': 0.006999197187038849}. Best is trial 19 with value: 0.3293677396367205.
[I 2025-12-17 06:46:26,724] Trial 21 finished with value: 0.21219303352150584 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04688438532151159, 'max_depth': 8, 'subsample': 0.8346851509135716, 'colsample_bytree': 0.5394079607516273, 'reg_alpha': 0.008312891788370348, 'reg_lambda': 0.0003963503644774612}. Best is trial 19 with value: 0.3293677396367205.
[I 2025-12-17 06:46:32,097] Trial 22 finished with value: 0.09819267618647115 and parameters: {'n_estimators': 1200, 'learning_rate': 0.1452730274082715, 'max_depth': 9, 'subsample': 0.7680283665318948, 'colsample_bytree': 0.6239396370821152, 'reg_alpha': 0.0004367891718165025, 'reg_lambda': 0.00010667065854738411}. Best is trial 19 with value: 0.3293677396367205.
[I 2025-12-17 06:46:38,320] Trial 23 finished with value: 0.22877206080826618 and parameters: {'n_estimators': 1500, 'learning_rate': 0.08045030078215551, 'max_depth': 8, 'subsample': 0.6799180846622596, 'colsample_bytree': 0.5397713407151024, 'reg_alpha': 0.09081561707334584, 'reg_lambda': 0.0024164974292498758}. Best is trial 19 with value: 0.3293677396367205.
[I 2025-12-17 06:46:47,844] Trial 24 finished with value: 0.27635607532321604 and parameters: {'n_estimators': 900, 'learning_rate': 0.009461926359828579, 'max_depth': 7, 'subsample': 0.8179316265733922, 'colsample_bytree': 0.5255383979452894, 'reg_alpha': 0.015878811766736566, 'reg_lambda': 0.0005411291077338081}. Best is trial 19 with value: 0.3293677396367205.

Best R2: 0.3294

[I 2025-12-17 06:46:50,146] A new study created in memory with name: XGB_state_1_Dry_Clover_g

Saved -> xgb_state_0_Dry_Green_g.pkl

------------------------------
 PROCESSING STATE: 1 (state_1)
------------------------------
Samples: 276
Optimizing state_1_Dry_Clover_g...

[I 2025-12-17 06:47:09,413] Trial 0 finished with value: -2.0090916760174435 and parameters: {'n_estimators': 1900, 'learning_rate': 0.009210912049117068, 'max_depth': 7, 'subsample': 0.573842005646954, 'colsample_bytree': 0.5124146365843839, 'reg_alpha': 0.00034722238093315585, 'reg_lambda': 0.4683128954271398}. Best is trial 0 with value: -2.0090916760174435.
[I 2025-12-17 06:47:15,945] Trial 1 finished with value: -3.4476939153306105 and parameters: {'n_estimators': 1300, 'learning_rate': 0.13883836664266738, 'max_depth': 7, 'subsample': 0.570598782288472, 'colsample_bytree': 0.6368328304365652, 'reg_alpha': 0.0017525976323150385, 'reg_lambda': 0.0010797737335635478}. Best is trial 0 with value: -2.0090916760174435.
[I 2025-12-17 06:47:49,096] Trial 2 finished with value: -2.126000670442208 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0034943509418472935, 'max_depth': 8, 'subsample': 0.6467168805808297, 'colsample_bytree': 0.8828454950122929, 'reg_alpha': 0.0031642190695503115, 'reg_lambda': 0.0009353039911561168}. Best is trial 0 with value: -2.0090916760174435.
[I 2025-12-17 06:48:14,318] Trial 3 finished with value: -1.9932500970729956 and parameters: {'n_estimators': 2000, 'learning_rate': 0.002226597769617553, 'max_depth': 7, 'subsample': 0.6248809449532122, 'colsample_bytree': 0.6278813993783066, 'reg_alpha': 0.05528632078910968, 'reg_lambda': 0.0024005523419045995}. Best is trial 3 with value: -1.9932500970729956.
[I 2025-12-17 06:48:18,371] Trial 4 finished with value: -0.7563510488670069 and parameters: {'n_estimators': 900, 'learning_rate': 0.005526664042644418, 'max_depth': 3, 'subsample': 0.8878444421025558, 'colsample_bytree': 0.7138279667869716, 'reg_alpha': 0.006444978139095373, 'reg_lambda': 1.5513162430948346}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:19,756] Trial 5 finished with value: -1.6258461212434654 and parameters: {'n_estimators': 300, 'learning_rate': 0.006262236894931598, 'max_depth': 3, 'subsample': 0.8653013152130202, 'colsample_bytree': 0.5602615629776919, 'reg_alpha': 0.0006701836385499804, 'reg_lambda': 0.06222391347393099}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:25,802] Trial 6 finished with value: -1.6326037669554725 and parameters: {'n_estimators': 700, 'learning_rate': 0.005373492073987645, 'max_depth': 6, 'subsample': 0.660585144013621, 'colsample_bytree': 0.6070807262088529, 'reg_alpha': 6.4154728362845574, 'reg_lambda': 0.0001763672265079276}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:29,362] Trial 7 finished with value: -2.5584060849220256 and parameters: {'n_estimators': 500, 'learning_rate': 0.11428804082130918, 'max_depth': 7, 'subsample': 0.6634049214097236, 'colsample_bytree': 0.6900611773981719, 'reg_alpha': 0.0008485092824386055, 'reg_lambda': 0.0023079524184124317}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:33,706] Trial 8 finished with value: -2.8664920033416426 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0012188970626788754, 'max_depth': 3, 'subsample': 0.8995296047743309, 'colsample_bytree': 0.5422989424133232, 'reg_alpha': 0.014166091516378869, 'reg_lambda': 0.9724321597125811}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:39,030] Trial 9 finished with value: -1.4588110183390461 and parameters: {'n_estimators': 1200, 'learning_rate': 0.005592268434469311, 'max_depth': 3, 'subsample': 0.5633446310153949, 'colsample_bytree': 0.6474960219777643, 'reg_alpha': 0.003980931081571016, 'reg_lambda': 0.01477282310870459}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:49,700] Trial 10 finished with value: -1.0876078019020758 and parameters: {'n_estimators': 1600, 'learning_rate': 0.034370596803790676, 'max_depth': 5, 'subsample': 0.8136813400711804, 'colsample_bytree': 0.8147690160787575, 'reg_alpha': 0.18022630775161555, 'reg_lambda': 6.68934497040728}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:48:59,440] Trial 11 finished with value: -1.1023084027314183 and parameters: {'n_estimators': 1400, 'learning_rate': 0.032657596457284, 'max_depth': 5, 'subsample': 0.7864467332730329, 'colsample_bytree': 0.8014796169087841, 'reg_alpha': 0.2835892143036914, 'reg_lambda': 7.695112615274798}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:10,065] Trial 12 finished with value: -1.2129895626511495 and parameters: {'n_estimators': 1500, 'learning_rate': 0.02511887208942734, 'max_depth': 5, 'subsample': 0.7857652018648041, 'colsample_bytree': 0.7913180609435441, 'reg_alpha': 0.2559841773327835, 'reg_lambda': 6.556065113333922}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:15,459] Trial 13 finished with value: -1.0916815744047306 and parameters: {'n_estimators': 900, 'learning_rate': 0.02172223685343122, 'max_depth': 4, 'subsample': 0.816428183302772, 'colsample_bytree': 0.7673803531771622, 'reg_alpha': 1.3681493043578958, 'reg_lambda': 0.9403950870304827}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:23,197] Trial 14 finished with value: -1.1176622215152847 and parameters: {'n_estimators': 1700, 'learning_rate': 0.0534663628660604, 'max_depth': 5, 'subsample': 0.7472148248391934, 'colsample_bytree': 0.8749330122559235, 'reg_alpha': 0.03130369517949927, 'reg_lambda': 0.16753794612016554}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:32,275] Trial 15 finished with value: -1.6544191248871167 and parameters: {'n_estimators': 1600, 'learning_rate': 0.013343183474390048, 'max_depth': 4, 'subsample': 0.8500551811205483, 'colsample_bytree': 0.7316876298489395, 'reg_alpha': 0.00012793305049426675, 'reg_lambda': 2.8872711403853453}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:37,545] Trial 16 finished with value: -0.9760321903493234 and parameters: {'n_estimators': 1000, 'learning_rate': 0.057021504708008035, 'max_depth': 4, 'subsample': 0.7317921812576293, 'colsample_bytree': 0.8397406784952046, 'reg_alpha': 0.16866049149785864, 'reg_lambda': 2.0737540953414664}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:41,347] Trial 17 finished with value: -1.2885758034743355 and parameters: {'n_estimators': 900, 'learning_rate': 0.06798767342589516, 'max_depth': 4, 'subsample': 0.7319730210263307, 'colsample_bytree': 0.716656433988525, 'reg_alpha': 0.0069958982502950455, 'reg_lambda': 0.028375038361240962}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:49,511] Trial 18 finished with value: -1.7635602889233437 and parameters: {'n_estimators': 700, 'learning_rate': 0.014055091095334076, 'max_depth': 9, 'subsample': 0.5068031379928736, 'colsample_bytree': 0.8350550426534524, 'reg_alpha': 0.9139863937325804, 'reg_lambda': 0.18462476510292009}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:56,023] Trial 19 finished with value: -1.3596787878217702 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0023048403971053398, 'max_depth': 4, 'subsample': 0.7085059652528337, 'colsample_bytree': 0.7487525203157276, 'reg_alpha': 0.07273564030970457, 'reg_lambda': 1.6223357702619339}. Best is trial 4 with value: -0.7563510488670069.
[I 2025-12-17 06:49:58,855] Trial 20 finished with value: -0.6944928121626757 and parameters: {'n_estimators': 700, 'learning_rate': 0.06803818027020483, 'max_depth': 3, 'subsample': 0.8972162345730005, 'colsample_bytree': 0.8499796718295817, 'reg_alpha': 0.01773605336352524, 'reg_lambda': 0.2624408427018886}. Best is trial 20 with value: -0.6944928121626757.
[I 2025-12-17 06:50:01,615] Trial 21 finished with value: -0.6964755359097599 and parameters: {'n_estimators': 700, 'learning_rate': 0.07155179161435814, 'max_depth': 3, 'subsample': 0.8952606187315251, 'colsample_bytree': 0.8525866883001331, 'reg_alpha': 0.01593804597921017, 'reg_lambda': 0.2514394314629942}. Best is trial 20 with value: -0.6944928121626757.
[I 2025-12-17 06:50:04,201] Trial 22 finished with value: -0.7495249265403365 and parameters: {'n_estimators': 700, 'learning_rate': 0.08834271341203831, 'max_depth': 3, 'subsample': 0.8955332586445832, 'colsample_bytree': 0.8986873402159435, 'reg_alpha': 0.014652650821139666, 'reg_lambda': 0.24604010452654873}. Best is trial 20 with value: -0.6944928121626757.
[I 2025-12-17 06:50:06,535] Trial 23 finished with value: -1.2145450050495321 and parameters: {'n_estimators': 600, 'learning_rate': 0.09813872656959198, 'max_depth': 3, 'subsample': 0.8410649174592306, 'colsample_bytree': 0.8991717529261455, 'reg_alpha': 0.019015628273793765, 'reg_lambda': 0.23417151516325155}. Best is trial 20 with value: -0.6944928121626757.
[I 2025-12-17 06:50:08,040] Trial 24 finished with value: -0.9779418596064857 and parameters: {'n_estimators': 300, 'learning_rate': 0.07462128554262243, 'max_depth': 3, 'subsample': 0.8752539683433184, 'colsample_bytree': 0.8396423969770034, 'reg_alpha': 0.013406892243680803, 'reg_lambda': 0.06271362069176326}. Best is trial 20 with value: -0.6944928121626757.

Best R2: -0.6945

[I 2025-12-17 06:50:08,958] A new study created in memory with name: XGB_state_1_Dry_Dead_g

Saved -> xgb_state_1_Dry_Clover_g.pkl
Optimizing state_1_Dry_Dead_g...

[I 2025-12-17 06:50:18,396] Trial 0 finished with value: -0.11923397331981575 and parameters: {'n_estimators': 600, 'learning_rate': 0.013244393075240663, 'max_depth': 7, 'subsample': 0.623429306550416, 'colsample_bytree': 0.6177351576515221, 'reg_alpha': 1.0353116212358733, 'reg_lambda': 1.0457703717355653}. Best is trial 0 with value: -0.11923397331981575.
[I 2025-12-17 06:50:49,567] Trial 1 finished with value: -0.01951566497596574 and parameters: {'n_estimators': 1300, 'learning_rate': 0.001512930218918002, 'max_depth': 9, 'subsample': 0.5023058394229345, 'colsample_bytree': 0.6839320781455829, 'reg_alpha': 7.299330696014398, 'reg_lambda': 0.21635065675664206}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:00,461] Trial 2 finished with value: -0.14411508861299618 and parameters: {'n_estimators': 400, 'learning_rate': 0.003307474667258995, 'max_depth': 8, 'subsample': 0.8765679051472534, 'colsample_bytree': 0.6483766900072989, 'reg_alpha': 0.3379377678725465, 'reg_lambda': 0.000332339469105223}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:02,042] Trial 3 finished with value: -0.0555005033028417 and parameters: {'n_estimators': 300, 'learning_rate': 0.02025779452213405, 'max_depth': 3, 'subsample': 0.6750289263461082, 'colsample_bytree': 0.8773170818973923, 'reg_alpha': 9.067997946250852, 'reg_lambda': 9.754812138306995}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:08,223] Trial 4 finished with value: -0.1201741021533175 and parameters: {'n_estimators': 1300, 'learning_rate': 0.012981880446141925, 'max_depth': 3, 'subsample': 0.6316028553506935, 'colsample_bytree': 0.6201500798412181, 'reg_alpha': 0.00019471204037817592, 'reg_lambda': 1.6086042694896887}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:14,598] Trial 5 finished with value: -0.16680211684602064 and parameters: {'n_estimators': 900, 'learning_rate': 0.004888712995974958, 'max_depth': 4, 'subsample': 0.6705632209259875, 'colsample_bytree': 0.7873335635669422, 'reg_alpha': 4.02383393922363, 'reg_lambda': 0.04583686285366293}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:27,446] Trial 6 finished with value: -0.09869019912978666 and parameters: {'n_estimators': 700, 'learning_rate': 0.030814181714463065, 'max_depth': 9, 'subsample': 0.5866743093046274, 'colsample_bytree': 0.5686542447996674, 'reg_alpha': 0.8022159438177455, 'reg_lambda': 9.299570240736113}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:32,428] Trial 7 finished with value: -0.22065529872807857 and parameters: {'n_estimators': 700, 'learning_rate': 0.02633694140952801, 'max_depth': 4, 'subsample': 0.7722387806823652, 'colsample_bytree': 0.8307105821860722, 'reg_alpha': 0.017177494587106525, 'reg_lambda': 0.003982250408828961}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:38,612] Trial 8 finished with value: -0.049847816755972746 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07898852402806764, 'max_depth': 3, 'subsample': 0.541983682889317, 'colsample_bytree': 0.5989219569937176, 'reg_alpha': 5.528040296822229, 'reg_lambda': 3.3791769452118685}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:42,078] Trial 9 finished with value: -0.14192735183615396 and parameters: {'n_estimators': 700, 'learning_rate': 0.043374299373733785, 'max_depth': 3, 'subsample': 0.6609804162611375, 'colsample_bytree': 0.7819293752674006, 'reg_alpha': 0.002813400161837832, 'reg_lambda': 0.06581351363310078}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:51:57,690] Trial 10 finished with value: -0.06511991145125401 and parameters: {'n_estimators': 1500, 'learning_rate': 0.001183043620471813, 'max_depth': 6, 'subsample': 0.5103038486925138, 'colsample_bytree': 0.5120290960399891, 'reg_alpha': 0.0607998569285182, 'reg_lambda': 0.2633689520752107}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:52:05,716] Trial 11 finished with value: -0.09495334451137216 and parameters: {'n_estimators': 1900, 'learning_rate': 0.11102572706556087, 'max_depth': 6, 'subsample': 0.5220872451645461, 'colsample_bytree': 0.7057947536324976, 'reg_alpha': 6.751388965583699, 'reg_lambda': 0.584030938317116}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:52:21,810] Trial 12 finished with value: -0.4403069213208928 and parameters: {'n_estimators': 2000, 'learning_rate': 0.13646722625514277, 'max_depth': 9, 'subsample': 0.5417932122739503, 'colsample_bytree': 0.6946147840505427, 'reg_alpha': 0.2754242507467514, 'reg_lambda': 0.006230386086537378}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:52:39,168] Trial 13 finished with value: -0.1306438024337907 and parameters: {'n_estimators': 1700, 'learning_rate': 0.0014718624311948977, 'max_depth': 5, 'subsample': 0.7480458697600253, 'colsample_bytree': 0.7090595799762204, 'reg_alpha': 1.9518114344600683, 'reg_lambda': 0.16212376550396307}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:52:52,882] Trial 14 finished with value: -0.07372117503648548 and parameters: {'n_estimators': 1100, 'learning_rate': 0.004695888416919392, 'max_depth': 7, 'subsample': 0.5858704398455494, 'colsample_bytree': 0.5440474684510255, 'reg_alpha': 0.0903529030080759, 'reg_lambda': 2.7282199228492243}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:53:01,536] Trial 15 finished with value: -0.27140427854030746 and parameters: {'n_estimators': 1600, 'learning_rate': 0.05795517191748509, 'max_depth': 5, 'subsample': 0.5645149783703249, 'colsample_bytree': 0.6614811360517496, 'reg_alpha': 0.0029032108170591697, 'reg_lambda': 0.01329165105468515}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:53:32,754] Trial 16 finished with value: -0.18458493216896724 and parameters: {'n_estimators': 1300, 'learning_rate': 0.0024134516861285373, 'max_depth': 8, 'subsample': 0.7371848168248079, 'colsample_bytree': 0.5842728959972419, 'reg_alpha': 0.010526168816885043, 'reg_lambda': 0.0009899465606329491}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:54:11,888] Trial 17 finished with value: -0.22805581065680447 and parameters: {'n_estimators': 1800, 'learning_rate': 0.006300270037350541, 'max_depth': 8, 'subsample': 0.5113278090582551, 'colsample_bytree': 0.759692596369415, 'reg_alpha': 0.23984553658779018, 'reg_lambda': 0.23197388993010387}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:54:18,757] Trial 18 finished with value: -0.03988891628000002 and parameters: {'n_estimators': 1400, 'learning_rate': 0.06690079177073685, 'max_depth': 5, 'subsample': 0.8202651476594817, 'colsample_bytree': 0.7422676040107967, 'reg_alpha': 2.838690425440547, 'reg_lambda': 2.583638371673782}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:54:29,623] Trial 19 finished with value: -0.19368695687148788 and parameters: {'n_estimators': 1100, 'learning_rate': 0.007829075462300066, 'max_depth': 5, 'subsample': 0.8312330260175818, 'colsample_bytree': 0.7437480159824795, 'reg_alpha': 1.5324980559906949, 'reg_lambda': 0.5710928413003086}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:54:52,001] Trial 20 finished with value: -0.24836840691396236 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0020446328775394424, 'max_depth': 6, 'subsample': 0.8108453732459864, 'colsample_bytree': 0.8425157695460701, 'reg_alpha': 0.0003235753318532417, 'reg_lambda': 0.00010767689409893431}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:54:56,236] Trial 21 finished with value: -0.1333829288496545 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07240103733156648, 'max_depth': 4, 'subsample': 0.8890267243479923, 'colsample_bytree': 0.6706560399286785, 'reg_alpha': 2.519185774682991, 'reg_lambda': 4.050410406762153}. Best is trial 1 with value: -0.01951566497596574.
[I 2025-12-17 06:55:05,801] Trial 22 finished with value: -0.013991715324695592 and parameters: {'n_estimators': 1600, 'learning_rate': 0.08638047132656385, 'max_depth': 7, 'subsample': 0.5547274046907249, 'colsample_bytree': 0.7381784427486531, 'reg_alpha': 9.49437118934298, 'reg_lambda': 3.642554704031774}. Best is trial 22 with value: -0.013991715324695592.
[I 2025-12-17 06:55:15,899] Trial 23 finished with value: -0.025426439150969593 and parameters: {'n_estimators': 1500, 'learning_rate': 0.042758484540209016, 'max_depth': 7, 'subsample': 0.7192547961276681, 'colsample_bytree': 0.7424521307845101, 'reg_alpha': 9.69074536017919, 'reg_lambda': 0.6709866086112178}. Best is trial 22 with value: -0.013991715324695592.
[I 2025-12-17 06:55:28,495] Trial 24 finished with value: -0.2947795255640674 and parameters: {'n_estimators': 1600, 'learning_rate': 0.04305439752229846, 'max_depth': 7, 'subsample': 0.7219473685690341, 'colsample_bytree': 0.7914277666387204, 'reg_alpha': 0.6448223371817401, 'reg_lambda': 0.15175131431835434}. Best is trial 22 with value: -0.013991715324695592.

Best R2: -0.0140

[I 2025-12-17 06:55:31,574] A new study created in memory with name: XGB_state_1_Dry_Green_g

Saved -> xgb_state_1_Dry_Dead_g.pkl
Optimizing state_1_Dry_Green_g...

[I 2025-12-17 06:55:39,115] Trial 0 finished with value: 0.38079282026666234 and parameters: {'n_estimators': 1600, 'learning_rate': 0.14846346164188567, 'max_depth': 6, 'subsample': 0.8796869782916543, 'colsample_bytree': 0.891196003295992, 'reg_alpha': 0.364811892122685, 'reg_lambda': 8.732727463344101}. Best is trial 0 with value: 0.38079282026666234.
[I 2025-12-17 06:55:49,247] Trial 1 finished with value: 0.2731591290616883 and parameters: {'n_estimators': 1600, 'learning_rate': 0.054664443671690356, 'max_depth': 7, 'subsample': 0.6962030858392865, 'colsample_bytree': 0.8416151013557855, 'reg_alpha': 0.007113587693172511, 'reg_lambda': 0.00013305362980592394}. Best is trial 0 with value: 0.38079282026666234.
[I 2025-12-17 06:55:53,310] Trial 2 finished with value: 0.3101575633346515 and parameters: {'n_estimators': 900, 'learning_rate': 0.001663648054363835, 'max_depth': 3, 'subsample': 0.8768291268520872, 'colsample_bytree': 0.6114594489634908, 'reg_alpha': 0.016646497403344188, 'reg_lambda': 0.6272073795669328}. Best is trial 0 with value: 0.38079282026666234.
[I 2025-12-17 06:56:02,766] Trial 3 finished with value: 0.3822032524794948 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09524241835022546, 'max_depth': 8, 'subsample': 0.7821777175114293, 'colsample_bytree': 0.6871019794562996, 'reg_alpha': 3.9760842202585263, 'reg_lambda': 9.159840734596937}. Best is trial 3 with value: 0.3822032524794948.
[I 2025-12-17 06:56:06,455] Trial 4 finished with value: 0.21804257803518795 and parameters: {'n_estimators': 400, 'learning_rate': 0.0019396135014197922, 'max_depth': 5, 'subsample': 0.7221801324157104, 'colsample_bytree': 0.6153170326023691, 'reg_alpha': 0.521749304116343, 'reg_lambda': 0.006764126201173911}. Best is trial 3 with value: 0.3822032524794948.
[I 2025-12-17 06:56:24,874] Trial 5 finished with value: 0.34077742523198984 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0017190361273652327, 'max_depth': 9, 'subsample': 0.6911069416142516, 'colsample_bytree': 0.6530139258288543, 'reg_alpha': 3.161640402515905, 'reg_lambda': 0.06757737387259764}. Best is trial 3 with value: 0.3822032524794948.
[I 2025-12-17 06:56:33,190] Trial 6 finished with value: 0.3942910828237336 and parameters: {'n_estimators': 1400, 'learning_rate': 0.01575914134045792, 'max_depth': 4, 'subsample': 0.7134651933551772, 'colsample_bytree': 0.8175711766394715, 'reg_alpha': 0.05686364042755803, 'reg_lambda': 2.006032488127389}. Best is trial 6 with value: 0.3942910828237336.
[I 2025-12-17 06:56:41,774] Trial 7 finished with value: 0.27989280606128697 and parameters: {'n_estimators': 900, 'learning_rate': 0.003888031595220101, 'max_depth': 5, 'subsample': 0.8066192454537278, 'colsample_bytree': 0.7322684467174271, 'reg_alpha': 0.28006180637779976, 'reg_lambda': 0.00026814931162061985}. Best is trial 6 with value: 0.3942910828237336.
[I 2025-12-17 06:56:57,937] Trial 8 finished with value: 0.30990553390186126 and parameters: {'n_estimators': 1900, 'learning_rate': 0.009928497491881093, 'max_depth': 5, 'subsample': 0.8513373492650709, 'colsample_bytree': 0.6240673715637566, 'reg_alpha': 0.02938237056364049, 'reg_lambda': 0.03308943102527896}. Best is trial 6 with value: 0.3942910828237336.
[I 2025-12-17 06:57:08,240] Trial 9 finished with value: 0.3126970288968278 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0013811581242673164, 'max_depth': 5, 'subsample': 0.5691059540953184, 'colsample_bytree': 0.7642928231098888, 'reg_alpha': 0.050307936453913286, 'reg_lambda': 0.0009192043185952388}. Best is trial 6 with value: 0.3942910828237336.
[I 2025-12-17 06:57:10,474] Trial 10 finished with value: 0.4176635041306128 and parameters: {'n_estimators': 500, 'learning_rate': 0.027406374669827996, 'max_depth': 3, 'subsample': 0.5886733288849146, 'colsample_bytree': 0.5365801025911989, 'reg_alpha': 0.0001800757403784339, 'reg_lambda': 1.006346637858379}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:11,824] Trial 11 finished with value: 0.4088041982882832 and parameters: {'n_estimators': 300, 'learning_rate': 0.021389938161810406, 'max_depth': 3, 'subsample': 0.5531718682459162, 'colsample_bytree': 0.5091340419800549, 'reg_alpha': 0.00015297350107438092, 'reg_lambda': 0.564722299819584}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:13,188] Trial 12 finished with value: 0.41400748705947266 and parameters: {'n_estimators': 300, 'learning_rate': 0.02704439936332325, 'max_depth': 3, 'subsample': 0.501345314683989, 'colsample_bytree': 0.5445395668966649, 'reg_alpha': 0.00010611867817745361, 'reg_lambda': 0.36050351227066607}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:15,804] Trial 13 finished with value: 0.4041967150774433 and parameters: {'n_estimators': 600, 'learning_rate': 0.037212820922904066, 'max_depth': 3, 'subsample': 0.5195275505500878, 'colsample_bytree': 0.5024954803004082, 'reg_alpha': 0.00012349142393079605, 'reg_lambda': 0.15025722433439145}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:19,534] Trial 14 finished with value: 0.39283239252708735 and parameters: {'n_estimators': 600, 'learning_rate': 0.006487867114891406, 'max_depth': 4, 'subsample': 0.615819629423176, 'colsample_bytree': 0.5569653064538183, 'reg_alpha': 0.0017420494538869992, 'reg_lambda': 0.006523522821368096}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:23,148] Trial 15 finished with value: 0.39338372686378675 and parameters: {'n_estimators': 600, 'learning_rate': 0.03346724678553097, 'max_depth': 4, 'subsample': 0.6272331611128059, 'colsample_bytree': 0.559775094957393, 'reg_alpha': 0.0007769574141907885, 'reg_lambda': 0.3858842107860251}. Best is trial 10 with value: 0.4176635041306128.
[I 2025-12-17 06:57:24,500] Trial 16 finished with value: 0.46254211163266257 and parameters: {'n_estimators': 300, 'learning_rate': 0.022588343518901342, 'max_depth': 3, 'subsample': 0.5000005613330513, 'colsample_bytree': 0.5598488547508332, 'reg_alpha': 0.0008002952155440706, 'reg_lambda': 2.159217118033249}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:57:32,113] Trial 17 finished with value: 0.4293660567790427 and parameters: {'n_estimators': 800, 'learning_rate': 0.00951969841013039, 'max_depth': 6, 'subsample': 0.6123416612046653, 'colsample_bytree': 0.5814500241306906, 'reg_alpha': 0.0007767041309812419, 'reg_lambda': 2.236083304879511}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:57:41,480] Trial 18 finished with value: 0.4177636513657739 and parameters: {'n_estimators': 800, 'learning_rate': 0.008256078228915142, 'max_depth': 7, 'subsample': 0.6438965512602961, 'colsample_bytree': 0.6047375050454628, 'reg_alpha': 0.0012562215589624868, 'reg_lambda': 2.5035787019441287}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:57:54,997] Trial 19 finished with value: 0.4325857117673829 and parameters: {'n_estimators': 1100, 'learning_rate': 0.003804702560242227, 'max_depth': 9, 'subsample': 0.5366620664774194, 'colsample_bytree': 0.6675657102745592, 'reg_alpha': 0.004169438117643718, 'reg_lambda': 3.1205644578672262}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:58:19,398] Trial 20 finished with value: 0.40162868326295564 and parameters: {'n_estimators': 1200, 'learning_rate': 0.004399835243808308, 'max_depth': 9, 'subsample': 0.5251723006434355, 'colsample_bytree': 0.681949528368254, 'reg_alpha': 0.004237703878215531, 'reg_lambda': 0.011474945157351896}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:58:32,803] Trial 21 finished with value: 0.4288733825439093 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0034682963433652464, 'max_depth': 8, 'subsample': 0.5453496846430593, 'colsample_bytree': 0.6471581392305144, 'reg_alpha': 0.0005197241160290733, 'reg_lambda': 2.797392568763149}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:58:40,384] Trial 22 finished with value: 0.42781471915527464 and parameters: {'n_estimators': 800, 'learning_rate': 0.014165873918628606, 'max_depth': 6, 'subsample': 0.5902541745454413, 'colsample_bytree': 0.5872621895347723, 'reg_alpha': 0.005369220641254288, 'reg_lambda': 4.569497006385323}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:58:56,639] Trial 23 finished with value: 0.363527076033214 and parameters: {'n_estimators': 1200, 'learning_rate': 0.005699265908075112, 'max_depth': 7, 'subsample': 0.6458883212863284, 'colsample_bytree': 0.5748529296049427, 'reg_alpha': 0.0003742400908265507, 'reg_lambda': 0.10479838355643294}. Best is trial 16 with value: 0.46254211163266257.
[I 2025-12-17 06:59:08,777] Trial 24 finished with value: 0.39558598986750987 and parameters: {'n_estimators': 1000, 'learning_rate': 0.002619313654376354, 'max_depth': 8, 'subsample': 0.5046425739451659, 'colsample_bytree': 0.7283876609621978, 'reg_alpha': 0.0019221017512462456, 'reg_lambda': 1.5192824691265205}. Best is trial 16 with value: 0.46254211163266257.

Best R2: 0.4625

[I 2025-12-17 06:59:09,162] A new study created in memory with name: XGB_state_2_Dry_Clover_g

Saved -> xgb_state_1_Dry_Green_g.pkl

------------------------------
 PROCESSING STATE: 2 (state_2)
------------------------------
Samples: 224
Optimizing state_2_Dry_Clover_g...

[I 2025-12-17 06:59:15,484] Trial 0 finished with value: -3.234707104677672 and parameters: {'n_estimators': 1100, 'learning_rate': 0.0030278080300621393, 'max_depth': 4, 'subsample': 0.7456505754815225, 'colsample_bytree': 0.6078289058504444, 'reg_alpha': 0.011197275126380555, 'reg_lambda': 0.04052564634758794}. Best is trial 0 with value: -3.234707104677672.
[I 2025-12-17 06:59:22,790] Trial 1 finished with value: -4.365805584065366 and parameters: {'n_estimators': 1600, 'learning_rate': 0.14630938127892443, 'max_depth': 8, 'subsample': 0.6653315120373775, 'colsample_bytree': 0.7505611886454477, 'reg_alpha': 0.045168290939461266, 'reg_lambda': 4.439090620543726}. Best is trial 0 with value: -3.234707104677672.
[I 2025-12-17 06:59:32,324] Trial 2 finished with value: -2.170605247197063 and parameters: {'n_estimators': 1800, 'learning_rate': 0.008580041187522643, 'max_depth': 4, 'subsample': 0.703777701940323, 'colsample_bytree': 0.6546388833743816, 'reg_alpha': 0.2265563326337, 'reg_lambda': 4.6999873595981745}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 06:59:36,913] Trial 3 finished with value: -3.1847277818627426 and parameters: {'n_estimators': 500, 'learning_rate': 0.005936572904810936, 'max_depth': 6, 'subsample': 0.6117620183611291, 'colsample_bytree': 0.6587305118059598, 'reg_alpha': 0.2649406536834162, 'reg_lambda': 0.006832657807246455}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 06:59:41,498] Trial 4 finished with value: -2.894434377987048 and parameters: {'n_estimators': 800, 'learning_rate': 0.0033511444094441, 'max_depth': 4, 'subsample': 0.8154077104026087, 'colsample_bytree': 0.6505119774437473, 'reg_alpha': 0.03537226093544637, 'reg_lambda': 0.32358873446367786}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 06:59:43,255] Trial 5 finished with value: -2.9874288315218296 and parameters: {'n_estimators': 300, 'learning_rate': 0.0860067940386809, 'max_depth': 4, 'subsample': 0.676093176701035, 'colsample_bytree': 0.660429594522205, 'reg_alpha': 0.005854939106658667, 'reg_lambda': 0.060064230862626536}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 06:59:49,054] Trial 6 finished with value: -3.2791285386975786 and parameters: {'n_estimators': 1300, 'learning_rate': 0.10690103997807236, 'max_depth': 7, 'subsample': 0.5157474720422478, 'colsample_bytree': 0.7197678598122872, 'reg_alpha': 0.011295923437519438, 'reg_lambda': 0.6160200442780914}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 06:59:53,699] Trial 7 finished with value: -3.3500553896914402 and parameters: {'n_estimators': 500, 'learning_rate': 0.05366067116346071, 'max_depth': 8, 'subsample': 0.7781385160051584, 'colsample_bytree': 0.7217602169658015, 'reg_alpha': 0.0002503702825517529, 'reg_lambda': 1.0011240022423997}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:00,022] Trial 8 finished with value: -2.857190592292167 and parameters: {'n_estimators': 800, 'learning_rate': 0.056339990855298526, 'max_depth': 7, 'subsample': 0.7545789822576561, 'colsample_bytree': 0.5357160677002603, 'reg_alpha': 0.01502943441521863, 'reg_lambda': 3.7889255650724545}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:08,485] Trial 9 finished with value: -2.9468567048471415 and parameters: {'n_estimators': 1800, 'learning_rate': 0.09291359157487698, 'max_depth': 9, 'subsample': 0.7304635522658288, 'colsample_bytree': 0.8958902029427853, 'reg_alpha': 0.06254989370230082, 'reg_lambda': 0.002646004533784339}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:16,833] Trial 10 finished with value: -2.883422811519815 and parameters: {'n_estimators': 1900, 'learning_rate': 0.00100011357203687, 'max_depth': 3, 'subsample': 0.893560172356874, 'colsample_bytree': 0.8219327764099914, 'reg_alpha': 8.091988657881478, 'reg_lambda': 0.000282102071057897}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:24,649] Trial 11 finished with value: -2.3472301293701165 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019721838577477228, 'max_depth': 6, 'subsample': 0.8453008452532067, 'colsample_bytree': 0.5311230090642545, 'reg_alpha': 0.8266934549844802, 'reg_lambda': 8.21766444795859}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:32,705] Trial 12 finished with value: -2.2926727839767245 and parameters: {'n_estimators': 1400, 'learning_rate': 0.019666242671703804, 'max_depth': 5, 'subsample': 0.8930914351308107, 'colsample_bytree': 0.5089296792604299, 'reg_alpha': 1.7929299347846013, 'reg_lambda': 6.397344330447717}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:40,769] Trial 13 finished with value: -3.04487645542801 and parameters: {'n_estimators': 1500, 'learning_rate': 0.01736795027012195, 'max_depth': 5, 'subsample': 0.5773972516132182, 'colsample_bytree': 0.5886041967022392, 'reg_alpha': 3.91646579284376, 'reg_lambda': 0.19965491952698247}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:49,028] Trial 14 finished with value: -2.680815208790007 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00845973202470136, 'max_depth': 3, 'subsample': 0.8880886219555767, 'colsample_bytree': 0.5050219025649789, 'reg_alpha': 0.9634219774538905, 'reg_lambda': 1.5377112904520127}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:00:57,006] Trial 15 finished with value: -3.76401315882872 and parameters: {'n_estimators': 1500, 'learning_rate': 0.029179840449638856, 'max_depth': 5, 'subsample': 0.6152247138261666, 'colsample_bytree': 0.5818112747993468, 'reg_alpha': 0.19951217328098175, 'reg_lambda': 0.00011589887926140902}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:01:09,203] Trial 16 finished with value: -2.280840628600552 and parameters: {'n_estimators': 1700, 'learning_rate': 0.008409532929094085, 'max_depth': 5, 'subsample': 0.8023068267060346, 'colsample_bytree': 0.8091799697982694, 'reg_alpha': 1.5597530753904338, 'reg_lambda': 9.584310737288138}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:01:19,308] Trial 17 finished with value: -2.941908944069474 and parameters: {'n_estimators': 1700, 'learning_rate': 0.004524133715130454, 'max_depth': 4, 'subsample': 0.8058413649214017, 'colsample_bytree': 0.794331671972046, 'reg_alpha': 0.0007564447091365357, 'reg_lambda': 0.1444432084643023}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:01:33,651] Trial 18 finished with value: -3.0045919768207323 and parameters: {'n_estimators': 1800, 'learning_rate': 0.002207250826542707, 'max_depth': 5, 'subsample': 0.7015155249413528, 'colsample_bytree': 0.8697393656373749, 'reg_alpha': 0.24368655333788627, 'reg_lambda': 0.011191477965193018}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:01:41,933] Trial 19 finished with value: -2.6772345008376406 and parameters: {'n_estimators': 2000, 'learning_rate': 0.010596519718036497, 'max_depth': 3, 'subsample': 0.8351402651403892, 'colsample_bytree': 0.7703624089356156, 'reg_alpha': 9.553335125989772, 'reg_lambda': 1.6973661059735201}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:01:53,810] Trial 20 finished with value: -3.5298311129905793 and parameters: {'n_estimators': 1300, 'learning_rate': 0.00721782122467071, 'max_depth': 6, 'subsample': 0.7137138870662952, 'colsample_bytree': 0.8391701034857061, 'reg_alpha': 0.6467086631849788, 'reg_lambda': 0.0008209458307937388}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:02:02,344] Trial 21 finished with value: -2.221019698065019 and parameters: {'n_estimators': 1400, 'learning_rate': 0.017807936995531418, 'max_depth': 5, 'subsample': 0.8611298646560922, 'colsample_bytree': 0.6909669748423622, 'reg_alpha': 2.4674785538702606, 'reg_lambda': 9.970791388831389}. Best is trial 2 with value: -2.170605247197063.
[I 2025-12-17 07:02:12,936] Trial 22 finished with value: -2.1020822964397277 and parameters: {'n_estimators': 1700, 'learning_rate': 0.013206631642458085, 'max_depth': 5, 'subsample': 0.7784112434421624, 'colsample_bytree': 0.6939542953240267, 'reg_alpha': 2.972512135090072, 'reg_lambda': 9.938531868871882}. Best is trial 22 with value: -2.1020822964397277.
[I 2025-12-17 07:02:19,088] Trial 23 finished with value: -2.4825898851129136 and parameters: {'n_estimators': 1600, 'learning_rate': 0.03531359758017098, 'max_depth': 4, 'subsample': 0.8462143006556246, 'colsample_bytree': 0.6837441085924065, 'reg_alpha': 3.376581898901837, 'reg_lambda': 2.3049135183971443}. Best is trial 22 with value: -2.1020822964397277.
[I 2025-12-17 07:02:28,188] Trial 24 finished with value: -3.42450658906525 and parameters: {'n_estimators': 1300, 'learning_rate': 0.013404029583209364, 'max_depth': 5, 'subsample': 0.7737422374485771, 'colsample_bytree': 0.6277943428324877, 'reg_alpha': 0.12330908442585552, 'reg_lambda': 0.4915575483199355}. Best is trial 22 with value: -2.1020822964397277.

Best R2: -2.1021

[I 2025-12-17 07:02:31,707] A new study created in memory with name: XGB_state_2_Dry_Dead_g

Saved -> xgb_state_2_Dry_Clover_g.pkl
Optimizing state_2_Dry_Dead_g...

[I 2025-12-17 07:02:38,701] Trial 0 finished with value: 0.32996050440141456 and parameters: {'n_estimators': 1500, 'learning_rate': 0.002632782100401488, 'max_depth': 3, 'subsample': 0.8837018991041062, 'colsample_bytree': 0.8125285258374533, 'reg_alpha': 0.000494513941696339, 'reg_lambda': 0.00887691026123443}. Best is trial 0 with value: 0.32996050440141456.
[I 2025-12-17 07:02:50,964] Trial 1 finished with value: 0.3280160619712369 and parameters: {'n_estimators': 1300, 'learning_rate': 0.0023044892581522433, 'max_depth': 5, 'subsample': 0.8212619317606182, 'colsample_bytree': 0.756346706465709, 'reg_alpha': 0.00035228969430947926, 'reg_lambda': 0.006579099576001559}. Best is trial 0 with value: 0.32996050440141456.
[I 2025-12-17 07:02:54,038] Trial 2 finished with value: 0.379158240631312 and parameters: {'n_estimators': 900, 'learning_rate': 0.07220988078892267, 'max_depth': 3, 'subsample': 0.5643038859088019, 'colsample_bytree': 0.8477996573758275, 'reg_alpha': 2.2208621634293846, 'reg_lambda': 0.00393944563981058}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:02:57,956] Trial 3 finished with value: 0.20893225534068555 and parameters: {'n_estimators': 600, 'learning_rate': 0.0025623646223168757, 'max_depth': 4, 'subsample': 0.8365871618876513, 'colsample_bytree': 0.6857405618397032, 'reg_alpha': 1.3849457778655732, 'reg_lambda': 0.024077178123678333}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:05,210] Trial 4 finished with value: 0.3432587866304236 and parameters: {'n_estimators': 1100, 'learning_rate': 0.04708354912857378, 'max_depth': 7, 'subsample': 0.7297069188549963, 'colsample_bytree': 0.5711495172897065, 'reg_alpha': 2.8739578290105396, 'reg_lambda': 0.00013657271355426443}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:16,456] Trial 5 finished with value: 0.22595793238744627 and parameters: {'n_estimators': 1600, 'learning_rate': 0.08357651985330812, 'max_depth': 9, 'subsample': 0.557527187245672, 'colsample_bytree': 0.6482706582844774, 'reg_alpha': 2.7993337562083997, 'reg_lambda': 3.2261651181019606}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:17,930] Trial 6 finished with value: -0.6336309700158071 and parameters: {'n_estimators': 300, 'learning_rate': 0.0010717585513146271, 'max_depth': 3, 'subsample': 0.6256896922471329, 'colsample_bytree': 0.6485373413404403, 'reg_alpha': 0.0059864501813088, 'reg_lambda': 0.0005068653609217411}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:25,707] Trial 7 finished with value: 0.35937972581513455 and parameters: {'n_estimators': 2000, 'learning_rate': 0.023459850105894995, 'max_depth': 3, 'subsample': 0.8579021119550261, 'colsample_bytree': 0.5290226614713273, 'reg_alpha': 0.006894884837516946, 'reg_lambda': 0.4281724505197177}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:27,589] Trial 8 finished with value: 0.22364726173476868 and parameters: {'n_estimators': 400, 'learning_rate': 0.0039136548916792295, 'max_depth': 3, 'subsample': 0.8224084479790987, 'colsample_bytree': 0.6288243589097722, 'reg_alpha': 0.0659666312659491, 'reg_lambda': 0.0830831495680157}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:37,134] Trial 9 finished with value: 0.22496161475726692 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0768942431720007, 'max_depth': 6, 'subsample': 0.5459226754184654, 'colsample_bytree': 0.5918831203667619, 'reg_alpha': 0.0022148299604973485, 'reg_lambda': 0.0013014684670091421}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:03:49,139] Trial 10 finished with value: 0.2968569821912864 and parameters: {'n_estimators': 800, 'learning_rate': 0.010877478917682993, 'max_depth': 8, 'subsample': 0.66394354107364, 'colsample_bytree': 0.8869543806288013, 'reg_alpha': 0.18074734282867505, 'reg_lambda': 9.462766193270197}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:00,750] Trial 11 finished with value: 0.34508131661429364 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02364537810292315, 'max_depth': 5, 'subsample': 0.7369074451961073, 'colsample_bytree': 0.5140755558434599, 'reg_alpha': 0.012226490592692431, 'reg_lambda': 0.39686915489913815}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:07,932] Trial 12 finished with value: 0.34970850315367885 and parameters: {'n_estimators': 1100, 'learning_rate': 0.023157298216076747, 'max_depth': 4, 'subsample': 0.5035142875466561, 'colsample_bytree': 0.8902360242664938, 'reg_alpha': 0.250387057073156, 'reg_lambda': 0.2078498796867172}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:10,509] Trial 13 finished with value: 0.28182046644731845 and parameters: {'n_estimators': 800, 'learning_rate': 0.13437748879069955, 'max_depth': 4, 'subsample': 0.6230658999222072, 'colsample_bytree': 0.7662965636550546, 'reg_alpha': 9.940089382320497, 'reg_lambda': 0.7837732442553086}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:23,677] Trial 14 finished with value: 0.36164596762558 and parameters: {'n_estimators': 1700, 'learning_rate': 0.011354549477166416, 'max_depth': 5, 'subsample': 0.7648273904189004, 'colsample_bytree': 0.5174543028598735, 'reg_alpha': 0.00010524727651568228, 'reg_lambda': 0.001813521142585722}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:42,751] Trial 15 finished with value: 0.32337604741993364 and parameters: {'n_estimators': 1700, 'learning_rate': 0.010729480207206758, 'max_depth': 6, 'subsample': 0.7644365238525688, 'colsample_bytree': 0.8039428714912078, 'reg_alpha': 0.00015386716892844176, 'reg_lambda': 0.0016400506173234039}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:04:55,533] Trial 16 finished with value: 0.337370298979385 and parameters: {'n_estimators': 1400, 'learning_rate': 0.005833335947725231, 'max_depth': 5, 'subsample': 0.6783458241643803, 'colsample_bytree': 0.7135700979710421, 'reg_alpha': 0.4235234992286676, 'reg_lambda': 0.004368812320844877}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:06,436] Trial 17 finished with value: 0.3631812268327731 and parameters: {'n_estimators': 900, 'learning_rate': 0.039944132472521876, 'max_depth': 7, 'subsample': 0.5996401087485324, 'colsample_bytree': 0.8457129449883805, 'reg_alpha': 0.030204477456443918, 'reg_lambda': 0.0001415486227217265}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:17,148] Trial 18 finished with value: 0.37446627139700145 and parameters: {'n_estimators': 900, 'learning_rate': 0.04406966845279889, 'max_depth': 7, 'subsample': 0.5863631118109424, 'colsample_bytree': 0.8474532565417592, 'reg_alpha': 0.01767478100965251, 'reg_lambda': 0.00012104981209795106}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:22,028] Trial 19 finished with value: 0.26466188313795014 and parameters: {'n_estimators': 600, 'learning_rate': 0.1394727074764243, 'max_depth': 7, 'subsample': 0.5571697903410738, 'colsample_bytree': 0.844121683418209, 'reg_alpha': 0.0564725640841874, 'reg_lambda': 0.00037742603336254974}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:37,292] Trial 20 finished with value: 0.3378331731956984 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04340427063546253, 'max_depth': 9, 'subsample': 0.5016670472866975, 'colsample_bytree': 0.7654751685991731, 'reg_alpha': 0.002268631120671174, 'reg_lambda': 0.047353426562253116}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:47,827] Trial 21 finished with value: 0.3529746961602274 and parameters: {'n_estimators': 900, 'learning_rate': 0.04194311188229962, 'max_depth': 7, 'subsample': 0.6059033713317084, 'colsample_bytree': 0.83111456750319, 'reg_alpha': 0.028011124497080275, 'reg_lambda': 0.0001043490773635357}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:05:55,720] Trial 22 finished with value: 0.35866303417140666 and parameters: {'n_estimators': 600, 'learning_rate': 0.07595902695071619, 'max_depth': 8, 'subsample': 0.5691833309940107, 'colsample_bytree': 0.8612954202818349, 'reg_alpha': 0.10811428010369414, 'reg_lambda': 0.0004411060560190231}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:06:13,950] Trial 23 finished with value: 0.37443524228227654 and parameters: {'n_estimators': 1200, 'learning_rate': 0.03206321920737107, 'max_depth': 8, 'subsample': 0.5925394553409883, 'colsample_bytree': 0.7956654242941437, 'reg_alpha': 0.02538660563951127, 'reg_lambda': 0.00024900581970750457}. Best is trial 2 with value: 0.379158240631312.
[I 2025-12-17 07:06:35,591] Trial 24 finished with value: 0.3346000447388048 and parameters: {'n_estimators': 1300, 'learning_rate': 0.017241679369444207, 'max_depth': 8, 'subsample': 0.6411443223195148, 'colsample_bytree': 0.7909981725524013, 'reg_alpha': 0.5115907062001752, 'reg_lambda': 0.0003415224477447548}. Best is trial 2 with value: 0.379158240631312.

Best R2: 0.3792

[I 2025-12-17 07:06:36,556] A new study created in memory with name: XGB_state_2_Dry_Green_g

Saved -> xgb_state_2_Dry_Dead_g.pkl
Optimizing state_2_Dry_Green_g...

[I 2025-12-17 07:06:49,997] Trial 0 finished with value: 0.3203159935729827 and parameters: {'n_estimators': 1700, 'learning_rate': 0.004548041993261957, 'max_depth': 5, 'subsample': 0.6256954979436745, 'colsample_bytree': 0.739536427460689, 'reg_alpha': 0.10757373426766986, 'reg_lambda': 0.0009522097282221244}. Best is trial 0 with value: 0.3203159935729827.
[I 2025-12-17 07:07:04,597] Trial 1 finished with value: 0.277535344914734 and parameters: {'n_estimators': 1400, 'learning_rate': 0.002521304211618221, 'max_depth': 6, 'subsample': 0.7158328429939897, 'colsample_bytree': 0.5110988386070869, 'reg_alpha': 0.02888348770945616, 'reg_lambda': 0.0002626056479561095}. Best is trial 0 with value: 0.3203159935729827.
[I 2025-12-17 07:07:10,159] Trial 2 finished with value: 0.3282110361908306 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009125682540092002, 'max_depth': 4, 'subsample': 0.5981064166053781, 'colsample_bytree': 0.5285554278924077, 'reg_alpha': 0.0006269836265373767, 'reg_lambda': 0.1001826480546132}. Best is trial 2 with value: 0.3282110361908306.
[I 2025-12-17 07:07:22,842] Trial 3 finished with value: 0.2616417065503038 and parameters: {'n_estimators': 1700, 'learning_rate': 0.03251072447232085, 'max_depth': 8, 'subsample': 0.7054331793074508, 'colsample_bytree': 0.6670678995423233, 'reg_alpha': 0.0001561510846919403, 'reg_lambda': 1.6151623675187128}. Best is trial 2 with value: 0.3282110361908306.
[I 2025-12-17 07:07:29,011] Trial 4 finished with value: 0.3476217778740983 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05144689794668876, 'max_depth': 3, 'subsample': 0.5969271866456138, 'colsample_bytree': 0.7460298700969232, 'reg_alpha': 0.016086296470917395, 'reg_lambda': 0.042290413341603106}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:07:44,269] Trial 5 finished with value: 0.30957525077125786 and parameters: {'n_estimators': 1800, 'learning_rate': 0.019459296519558356, 'max_depth': 7, 'subsample': 0.5249705343666661, 'colsample_bytree': 0.6006674355101025, 'reg_alpha': 0.017465723996946406, 'reg_lambda': 0.24456369508447443}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:07:52,119] Trial 6 finished with value: 0.30227910939033464 and parameters: {'n_estimators': 700, 'learning_rate': 0.01755900904503316, 'max_depth': 6, 'subsample': 0.56010589848072, 'colsample_bytree': 0.8056334648177039, 'reg_alpha': 0.00019400359247314587, 'reg_lambda': 0.00044149809713886446}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:07:54,763] Trial 7 finished with value: 0.2621447765251098 and parameters: {'n_estimators': 300, 'learning_rate': 0.08769362770444512, 'max_depth': 6, 'subsample': 0.710645835199216, 'colsample_bytree': 0.6096369375964419, 'reg_alpha': 0.010900041642934115, 'reg_lambda': 7.07959574817667}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:07:58,682] Trial 8 finished with value: 0.31938955871090635 and parameters: {'n_estimators': 400, 'learning_rate': 0.02259448707799397, 'max_depth': 8, 'subsample': 0.6372168077567618, 'colsample_bytree': 0.5886627737634138, 'reg_alpha': 2.559241413324193, 'reg_lambda': 0.1606409225683011}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:01,792] Trial 9 finished with value: 0.21550165397226057 and parameters: {'n_estimators': 700, 'learning_rate': 0.0027253555976657472, 'max_depth': 3, 'subsample': 0.7132818654050099, 'colsample_bytree': 0.8423919162071927, 'reg_alpha': 0.00013756106545602942, 'reg_lambda': 9.526856989684559}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:06,785] Trial 10 finished with value: 0.2618682505036906 and parameters: {'n_estimators': 2000, 'learning_rate': 0.14114567872305805, 'max_depth': 3, 'subsample': 0.8248746465775921, 'colsample_bytree': 0.7529368291000121, 'reg_alpha': 0.5560756988964007, 'reg_lambda': 0.006586873847831026}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:14,178] Trial 11 finished with value: 0.31869707248421963 and parameters: {'n_estimators': 1200, 'learning_rate': 0.007139436486135348, 'max_depth': 4, 'subsample': 0.5978166925724512, 'colsample_bytree': 0.8997963679385133, 'reg_alpha': 0.0020691274119968893, 'reg_lambda': 0.01977745381734204}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:18,476] Trial 12 finished with value: 0.2238990727362586 and parameters: {'n_estimators': 900, 'learning_rate': 0.04957291168396918, 'max_depth': 4, 'subsample': 0.5087659196970018, 'colsample_bytree': 0.5014601822691155, 'reg_alpha': 0.001590473051230342, 'reg_lambda': 0.11725255767358361}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:26,218] Trial 13 finished with value: 0.27768522745663016 and parameters: {'n_estimators': 1300, 'learning_rate': 0.008913624664564237, 'max_depth': 4, 'subsample': 0.8252086003441981, 'colsample_bytree': 0.6768106229686957, 'reg_alpha': 0.001628938947657578, 'reg_lambda': 0.005662468424796991}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:30,525] Trial 14 finished with value: 0.21026451033088556 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0012664488904395748, 'max_depth': 3, 'subsample': 0.6511438050495258, 'colsample_bytree': 0.7361203065732266, 'reg_alpha': 0.004143401331674894, 'reg_lambda': 0.04164961319464683}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:36,992] Trial 15 finished with value: 0.29620803196146084 and parameters: {'n_estimators': 1500, 'learning_rate': 0.0676395216950569, 'max_depth': 5, 'subsample': 0.5912770107539566, 'colsample_bytree': 0.8074994635260585, 'reg_alpha': 0.17070438563430163, 'reg_lambda': 0.36579358297940073}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:08:56,906] Trial 16 finished with value: 0.29034379717842557 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011055005564910805, 'max_depth': 9, 'subsample': 0.7690228233487348, 'colsample_bytree': 0.555954682228279, 'reg_alpha': 0.000572318542321998, 'reg_lambda': 0.0033966035586899014}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:05,308] Trial 17 finished with value: 0.2500349404400679 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03476283421491955, 'max_depth': 5, 'subsample': 0.8946651867653161, 'colsample_bytree': 0.6538289380071777, 'reg_alpha': 0.09426307766814952, 'reg_lambda': 0.03694500885702154}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:08,705] Trial 18 finished with value: 0.2939256123502956 and parameters: {'n_estimators': 600, 'learning_rate': 0.004769161073329149, 'max_depth': 4, 'subsample': 0.5583729573776115, 'colsample_bytree': 0.6415789673397811, 'reg_alpha': 0.0076884516937714645, 'reg_lambda': 1.126725726480908}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:12,595] Trial 19 finished with value: 0.22048844963900147 and parameters: {'n_estimators': 1500, 'learning_rate': 0.13150237293925215, 'max_depth': 3, 'subsample': 0.643182505465677, 'colsample_bytree': 0.7098856282429546, 'reg_alpha': 7.284582256006669, 'reg_lambda': 0.9335473508972034}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:19,230] Trial 20 finished with value: 0.3310225178962016 and parameters: {'n_estimators': 1100, 'learning_rate': 0.013693004267803314, 'max_depth': 4, 'subsample': 0.5539791085231575, 'colsample_bytree': 0.7857908861532993, 'reg_alpha': 0.0006240047508364848, 'reg_lambda': 0.0171606031307469}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:25,841] Trial 21 finished with value: 0.32956480975088565 and parameters: {'n_estimators': 1100, 'learning_rate': 0.01675999689051508, 'max_depth': 4, 'subsample': 0.5483127133738344, 'colsample_bytree': 0.7751252704128411, 'reg_alpha': 0.0004454733284863397, 'reg_lambda': 0.017424048768153625}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:32,775] Trial 22 finished with value: 0.30783681998599677 and parameters: {'n_estimators': 1200, 'learning_rate': 0.037544085336192676, 'max_depth': 5, 'subsample': 0.5527804752356061, 'colsample_bytree': 0.7910866826102765, 'reg_alpha': 0.0005014178832230651, 'reg_lambda': 0.01496185983081149}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:36,259] Trial 23 finished with value: 0.3172437715993286 and parameters: {'n_estimators': 800, 'learning_rate': 0.015377119273984958, 'max_depth': 3, 'subsample': 0.5001980025274583, 'colsample_bytree': 0.7743150101303675, 'reg_alpha': 0.004448293435123477, 'reg_lambda': 0.0017555872778944113}. Best is trial 4 with value: 0.3476217778740983.
[I 2025-12-17 07:09:42,955] Trial 24 finished with value: 0.2671525484165102 and parameters: {'n_estimators': 1100, 'learning_rate': 0.023886923082253503, 'max_depth': 4, 'subsample': 0.538692647232618, 'colsample_bytree': 0.8496046146023704, 'reg_alpha': 0.0003798114620077873, 'reg_lambda': 0.010643347671867693}. Best is trial 4 with value: 0.3476217778740983.

Best R2: 0.3476

[I 2025-12-17 07:09:44,859] A new study created in memory with name: XGB_state_3_Dry_Clover_g

Saved -> xgb_state_2_Dry_Green_g.pkl

------------------------------
 PROCESSING STATE: 3 (state_3)
------------------------------
Samples: 64
Optimizing state_3_Dry_Clover_g...

[I 2025-12-17 07:09:49,870] Trial 0 finished with value: 0.41860709549833547 and parameters: {'n_estimators': 1200, 'learning_rate': 0.0015296775532295378, 'max_depth': 9, 'subsample': 0.8581702891660894, 'colsample_bytree': 0.7972245690985087, 'reg_alpha': 0.8076946757750191, 'reg_lambda': 0.038820858035760526}. Best is trial 0 with value: 0.41860709549833547.
[I 2025-12-17 07:09:53,757] Trial 1 finished with value: 0.43023911702695244 and parameters: {'n_estimators': 1700, 'learning_rate': 0.035554919255067687, 'max_depth': 6, 'subsample': 0.8745659715201765, 'colsample_bytree': 0.7576759544641154, 'reg_alpha': 0.0019926222084881745, 'reg_lambda': 0.0023019034115066075}. Best is trial 1 with value: 0.43023911702695244.
[I 2025-12-17 07:09:57,020] Trial 2 finished with value: 0.5021000912919434 and parameters: {'n_estimators': 1400, 'learning_rate': 0.032390480255314436, 'max_depth': 7, 'subsample': 0.5680967158560782, 'colsample_bytree': 0.6515447107095746, 'reg_alpha': 1.0731741093926042, 'reg_lambda': 0.002096334174576638}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:01,814] Trial 3 finished with value: 0.449549679989041 and parameters: {'n_estimators': 1600, 'learning_rate': 0.0042774486107235495, 'max_depth': 7, 'subsample': 0.834018964669957, 'colsample_bytree': 0.5649458499804688, 'reg_alpha': 8.012752845295593, 'reg_lambda': 0.00939338833399932}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:04,180] Trial 4 finished with value: 0.3799287601869912 and parameters: {'n_estimators': 1400, 'learning_rate': 0.13051492298866763, 'max_depth': 3, 'subsample': 0.6149859262447387, 'colsample_bytree': 0.8012954229921769, 'reg_alpha': 0.0009745416964316165, 'reg_lambda': 0.0467887583254546}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:05,026] Trial 5 finished with value: 0.32592880946702385 and parameters: {'n_estimators': 300, 'learning_rate': 0.006957460937571186, 'max_depth': 3, 'subsample': 0.5439618133835091, 'colsample_bytree': 0.8503351655240883, 'reg_alpha': 7.8700911842146075, 'reg_lambda': 1.2787478477781429}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:10,015] Trial 6 finished with value: 0.46556628752558105 and parameters: {'n_estimators': 900, 'learning_rate': 0.009256107432288217, 'max_depth': 6, 'subsample': 0.8378803710112868, 'colsample_bytree': 0.7556421296424826, 'reg_alpha': 0.0001956344374202315, 'reg_lambda': 0.00011545795114577956}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:13,503] Trial 7 finished with value: 0.4218383195720749 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08384831940185279, 'max_depth': 7, 'subsample': 0.8623391132769462, 'colsample_bytree': 0.5788803208161573, 'reg_alpha': 0.2731666133346646, 'reg_lambda': 0.4862032405632238}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:18,029] Trial 8 finished with value: 0.4917976268689266 and parameters: {'n_estimators': 1300, 'learning_rate': 0.00445204340520668, 'max_depth': 4, 'subsample': 0.7368804111109439, 'colsample_bytree': 0.8985263567599057, 'reg_alpha': 0.00015610899224789663, 'reg_lambda': 0.36738254748666355}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:19,432] Trial 9 finished with value: 0.17714358881739414 and parameters: {'n_estimators': 300, 'learning_rate': 0.0014959549573943872, 'max_depth': 6, 'subsample': 0.6213727364867433, 'colsample_bytree': 0.7672163553655784, 'reg_alpha': 0.04791942744741465, 'reg_lambda': 0.0025187894180092427}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:21,995] Trial 10 finished with value: 0.4616648237947927 and parameters: {'n_estimators': 800, 'learning_rate': 0.0275360837446218, 'max_depth': 9, 'subsample': 0.5186744856864062, 'colsample_bytree': 0.6547589284240821, 'reg_alpha': 0.020808495611042952, 'reg_lambda': 8.758873539706238}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:24,681] Trial 11 finished with value: 0.4633935014903438 and parameters: {'n_estimators': 1000, 'learning_rate': 0.025876555805134527, 'max_depth': 4, 'subsample': 0.7521545580131935, 'colsample_bytree': 0.6664043546340478, 'reg_alpha': 0.010703580480522387, 'reg_lambda': 0.0001503786694322625}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:30,074] Trial 12 finished with value: 0.48071784918385324 and parameters: {'n_estimators': 1300, 'learning_rate': 0.003327708611547063, 'max_depth': 5, 'subsample': 0.7322700371520076, 'colsample_bytree': 0.8809354682306628, 'reg_alpha': 0.00011203573712497817, 'reg_lambda': 0.2007991152521635}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:34,633] Trial 13 finished with value: 0.4747814889836373 and parameters: {'n_estimators': 1600, 'learning_rate': 0.016132096676193957, 'max_depth': 8, 'subsample': 0.6776198946178614, 'colsample_bytree': 0.6212243170918758, 'reg_alpha': 0.351379973301353, 'reg_lambda': 0.0014691840190730737}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:36,470] Trial 14 finished with value: 0.4330955281990317 and parameters: {'n_estimators': 700, 'learning_rate': 0.07029860875599218, 'max_depth': 4, 'subsample': 0.7837187038834739, 'colsample_bytree': 0.7000945436911795, 'reg_alpha': 1.8739817524986195, 'reg_lambda': 3.246253860759277}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:43,446] Trial 15 finished with value: 0.47427726705626716 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0038287281607433457, 'max_depth': 5, 'subsample': 0.6632825565564027, 'colsample_bytree': 0.5361188151191973, 'reg_alpha': 0.08782103382514261, 'reg_lambda': 0.10057033848870879}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:49,327] Trial 16 finished with value: 0.47522131943053236 and parameters: {'n_estimators': 1400, 'learning_rate': 0.012513228892417254, 'max_depth': 7, 'subsample': 0.5751535528776891, 'colsample_bytree': 0.7096924629103789, 'reg_alpha': 0.004470196592828424, 'reg_lambda': 0.00730640313561003}. Best is trial 2 with value: 0.5021000912919434.
[I 2025-12-17 07:10:52,174] Trial 17 finished with value: 0.5123823610117184 and parameters: {'n_estimators': 1100, 'learning_rate': 0.04268764239568602, 'max_depth': 5, 'subsample': 0.7138124437925827, 'colsample_bytree': 0.8968788598767025, 'reg_alpha': 0.0003721092718175262, 'reg_lambda': 0.0004487126260923012}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:10:54,452] Trial 18 finished with value: 0.5001452219829937 and parameters: {'n_estimators': 600, 'learning_rate': 0.04318327847418883, 'max_depth': 8, 'subsample': 0.6317214665533362, 'colsample_bytree': 0.6220708552810688, 'reg_alpha': 0.000657244198171602, 'reg_lambda': 0.0004611718166806993}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:10:56,724] Trial 19 finished with value: 0.4996462253016139 and parameters: {'n_estimators': 1100, 'learning_rate': 0.05726038052905567, 'max_depth': 5, 'subsample': 0.579708269735535, 'colsample_bytree': 0.5078094493051732, 'reg_alpha': 2.2257080162291776, 'reg_lambda': 0.00047125823881379297}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:10:59,633] Trial 20 finished with value: 0.4623766697907559 and parameters: {'n_estimators': 600, 'learning_rate': 0.01918152201720573, 'max_depth': 8, 'subsample': 0.7040405085894881, 'colsample_bytree': 0.8340270941219042, 'reg_alpha': 0.004782154402025127, 'reg_lambda': 0.012082526885655172}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:11:01,764] Trial 21 finished with value: 0.5003956221252133 and parameters: {'n_estimators': 500, 'learning_rate': 0.04396840056491813, 'max_depth': 8, 'subsample': 0.6370914632730367, 'colsample_bytree': 0.6154867240607276, 'reg_alpha': 0.00037159599098614873, 'reg_lambda': 0.0004883640212717483}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:11:03,069] Trial 22 finished with value: 0.3553006243411316 and parameters: {'n_estimators': 500, 'learning_rate': 0.1425562378073852, 'max_depth': 7, 'subsample': 0.5019042020857158, 'colsample_bytree': 0.6033665452137011, 'reg_alpha': 0.0003573329937125872, 'reg_lambda': 0.0005571497807565046}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:11:05,766] Trial 23 finished with value: 0.43893721907130967 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05036861739240419, 'max_depth': 8, 'subsample': 0.6546479447614201, 'colsample_bytree': 0.6618862861571495, 'reg_alpha': 0.001287910313360113, 'reg_lambda': 0.0012361845999141275}. Best is trial 17 with value: 0.5123823610117184.
[I 2025-12-17 07:11:09,205] Trial 24 finished with value: 0.4778203854359018 and parameters: {'n_estimators': 1800, 'learning_rate': 0.08817005898679071, 'max_depth': 6, 'subsample': 0.5852476361709473, 'colsample_bytree': 0.7267240200427048, 'reg_alpha': 0.15804366507734763, 'reg_lambda': 0.0001930089229423762}. Best is trial 17 with value: 0.5123823610117184.

Best R2: 0.5124

[I 2025-12-17 07:11:10,267] A new study created in memory with name: XGB_state_3_Dry_Dead_g

Saved -> xgb_state_3_Dry_Clover_g.pkl
Optimizing state_3_Dry_Dead_g...

[I 2025-12-17 07:11:13,523] Trial 0 finished with value: 1.0 and parameters: {'n_estimators': 2000, 'learning_rate': 0.004663679233758313, 'max_depth': 5, 'subsample': 0.875346267748881, 'colsample_bytree': 0.8737764231406773, 'reg_alpha': 0.009255491277505334, 'reg_lambda': 2.5992888751667964}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:15,481] Trial 1 finished with value: 1.0 and parameters: {'n_estimators': 1200, 'learning_rate': 0.026981912030383054, 'max_depth': 3, 'subsample': 0.7181614993553149, 'colsample_bytree': 0.6013568036044433, 'reg_alpha': 0.0004055691837151884, 'reg_lambda': 0.00021074325114449138}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:16,008] Trial 2 finished with value: 1.0 and parameters: {'n_estimators': 300, 'learning_rate': 0.012054560993287973, 'max_depth': 7, 'subsample': 0.8256988804310261, 'colsample_bytree': 0.8796795164115474, 'reg_alpha': 0.012253086023726758, 'reg_lambda': 0.049473031159536114}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:19,120] Trial 3 finished with value: 1.0 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0172594555850935, 'max_depth': 7, 'subsample': 0.6769006012094987, 'colsample_bytree': 0.6561272455028606, 'reg_alpha': 0.0035619813239280017, 'reg_lambda': 0.2501201006223623}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:20,590] Trial 4 finished with value: 1.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.018653825948104386, 'max_depth': 3, 'subsample': 0.8176328357826228, 'colsample_bytree': 0.6868720537472597, 'reg_alpha': 0.7958383599485561, 'reg_lambda': 0.0069327361396533576}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:23,876] Trial 5 finished with value: 1.0 and parameters: {'n_estimators': 2000, 'learning_rate': 0.028571874933964535, 'max_depth': 6, 'subsample': 0.7157437811028347, 'colsample_bytree': 0.8678650362186369, 'reg_alpha': 9.039627942904527, 'reg_lambda': 0.005548387779276229}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:24,899] Trial 6 finished with value: 1.0 and parameters: {'n_estimators': 600, 'learning_rate': 0.0018477608767948509, 'max_depth': 7, 'subsample': 0.5555499165539666, 'colsample_bytree': 0.7471565916765354, 'reg_alpha': 0.013807196287275622, 'reg_lambda': 0.00019184446409935982}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:26,402] Trial 7 finished with value: 1.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.002672064103163854, 'max_depth': 3, 'subsample': 0.8242283502407322, 'colsample_bytree': 0.6131477521735846, 'reg_alpha': 0.0001498199555664787, 'reg_lambda': 0.027483329849923254}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:29,531] Trial 8 finished with value: 1.0 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0020290862796251263, 'max_depth': 4, 'subsample': 0.6728929579499734, 'colsample_bytree': 0.8565917986232661, 'reg_alpha': 0.0032035491942016114, 'reg_lambda': 0.017459066216744187}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:30,522] Trial 9 finished with value: 1.0 and parameters: {'n_estimators': 600, 'learning_rate': 0.03845398342996945, 'max_depth': 4, 'subsample': 0.7454493404343145, 'colsample_bytree': 0.7047447257744544, 'reg_alpha': 0.0027509530892895974, 'reg_lambda': 0.01329697252242631}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:32,823] Trial 10 finished with value: 1.0 and parameters: {'n_estimators': 1400, 'learning_rate': 0.11235198922691861, 'max_depth': 9, 'subsample': 0.8906344200430547, 'colsample_bytree': 0.7910875027341309, 'reg_alpha': 0.15165751002836086, 'reg_lambda': 9.856317492984157}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:35,240] Trial 11 finished with value: 1.0 and parameters: {'n_estimators': 1500, 'learning_rate': 0.007207625569320682, 'max_depth': 5, 'subsample': 0.5766331714343509, 'colsample_bytree': 0.5248529080565956, 'reg_alpha': 0.00012315876562036138, 'reg_lambda': 0.00010150637581446963}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:37,693] Trial 12 finished with value: 1.0 and parameters: {'n_estimators': 1500, 'learning_rate': 0.005633025662202253, 'max_depth': 5, 'subsample': 0.6206149231252992, 'colsample_bytree': 0.5665069646077562, 'reg_alpha': 0.0005299063539517542, 'reg_lambda': 4.0701519631994}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:39,668] Trial 13 finished with value: 1.0 and parameters: {'n_estimators': 1200, 'learning_rate': 0.05984469755870792, 'max_depth': 4, 'subsample': 0.5064542725202791, 'colsample_bytree': 0.7944853193465273, 'reg_alpha': 0.08252889015866917, 'reg_lambda': 0.0008869722374969785}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:42,293] Trial 14 finished with value: 1.0 and parameters: {'n_estimators': 1600, 'learning_rate': 0.004868457812728878, 'max_depth': 5, 'subsample': 0.8903946552056119, 'colsample_bytree': 0.6094779445067366, 'reg_alpha': 0.0009306273360744189, 'reg_lambda': 0.682548682255843}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:45,087] Trial 15 finished with value: 1.0 and parameters: {'n_estimators': 1700, 'learning_rate': 0.009958815509340928, 'max_depth': 3, 'subsample': 0.7690003819885056, 'colsample_bytree': 0.5011256747113099, 'reg_alpha': 0.0006280014381551934, 'reg_lambda': 0.0014466047584202992}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:46,908] Trial 16 finished with value: 1.0 and parameters: {'n_estimators': 1100, 'learning_rate': 0.003338755760869248, 'max_depth': 9, 'subsample': 0.630729107269665, 'colsample_bytree': 0.6322434783340187, 'reg_alpha': 0.05067057793677322, 'reg_lambda': 0.20335694040297975}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:48,918] Trial 17 finished with value: 1.0 and parameters: {'n_estimators': 1200, 'learning_rate': 0.13490624278515673, 'max_depth': 6, 'subsample': 0.7810027284670022, 'colsample_bytree': 0.810232705706261, 'reg_alpha': 0.015558583435470752, 'reg_lambda': 1.2476055364765206}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:51,708] Trial 18 finished with value: 1.0 and parameters: {'n_estimators': 1700, 'learning_rate': 0.0011100827491720676, 'max_depth': 4, 'subsample': 0.8622598435223219, 'colsample_bytree': 0.5637620933921513, 'reg_alpha': 0.4306630983225266, 'reg_lambda': 0.0007527390745122754}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:53,197] Trial 19 finished with value: 1.0 and parameters: {'n_estimators': 900, 'learning_rate': 0.06064000901462571, 'max_depth': 8, 'subsample': 0.7299888139046964, 'colsample_bytree': 0.733358491721742, 'reg_alpha': 0.001488526889063599, 'reg_lambda': 0.09909790705528827}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:54,043] Trial 20 finished with value: 1.0 and parameters: {'n_estimators': 500, 'learning_rate': 0.024578988003397365, 'max_depth': 5, 'subsample': 0.7753859276139539, 'colsample_bytree': 0.5669568757565326, 'reg_alpha': 0.0003297420890836472, 'reg_lambda': 0.8330563753553001}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:54,582] Trial 21 finished with value: 1.0 and parameters: {'n_estimators': 300, 'learning_rate': 0.01176637855940748, 'max_depth': 7, 'subsample': 0.8343602641068572, 'colsample_bytree': 0.8957306607238644, 'reg_alpha': 0.010644299543429174, 'reg_lambda': 0.11948325964200256}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:55,115] Trial 22 finished with value: 1.0 and parameters: {'n_estimators': 300, 'learning_rate': 0.008940021909644897, 'max_depth': 6, 'subsample': 0.842903009712397, 'colsample_bytree': 0.8300096655434318, 'reg_alpha': 0.028981713164262304, 'reg_lambda': 0.0655375488807186}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:56,486] Trial 23 finished with value: 1.0 and parameters: {'n_estimators': 800, 'learning_rate': 0.014658355534907203, 'max_depth': 8, 'subsample': 0.7875615514423799, 'colsample_bytree': 0.8901894241758215, 'reg_alpha': 0.006988314296008639, 'reg_lambda': 0.002057027862621349}. Best is trial 0 with value: 1.0.
[I 2025-12-17 07:11:58,641] Trial 24 finished with value: 1.0 and parameters: {'n_estimators': 1300, 'learning_rate': 0.004012037643981008, 'max_depth': 8, 'subsample': 0.8662190213267007, 'colsample_bytree': 0.7664431969535911, 'reg_alpha': 1.8917605388418663, 'reg_lambda': 0.0003523928142585582}. Best is trial 0 with value: 1.0.

Best R2: 1.0000

[I 2025-12-17 07:11:59,752] A new study created in memory with name: XGB_state_3_Dry_Green_g

Saved -> xgb_state_3_Dry_Dead_g.pkl
Optimizing state_3_Dry_Green_g...

[I 2025-12-17 07:12:03,799] Trial 0 finished with value: 0.7028514757546863 and parameters: {'n_estimators': 1600, 'learning_rate': 0.012598798769127508, 'max_depth': 4, 'subsample': 0.8868276203170111, 'colsample_bytree': 0.6220210459667894, 'reg_alpha': 5.3750103357059125, 'reg_lambda': 0.31923781677658525}. Best is trial 0 with value: 0.7028514757546863.
[I 2025-12-17 07:12:05,772] Trial 1 finished with value: 0.42866599468607164 and parameters: {'n_estimators': 700, 'learning_rate': 0.002003091315175357, 'max_depth': 7, 'subsample': 0.7014564608814625, 'colsample_bytree': 0.5745386986925161, 'reg_alpha': 0.0009169602127935373, 'reg_lambda': 2.4763388651551255}. Best is trial 0 with value: 0.7028514757546863.
[I 2025-12-17 07:12:09,086] Trial 2 finished with value: 0.3206143968637634 and parameters: {'n_estimators': 1800, 'learning_rate': 0.0518955946262693, 'max_depth': 4, 'subsample': 0.7823316019731925, 'colsample_bytree': 0.7229063896694905, 'reg_alpha': 0.0010717600886167868, 'reg_lambda': 0.0001740861260308096}. Best is trial 0 with value: 0.7028514757546863.
[I 2025-12-17 07:12:13,025] Trial 3 finished with value: 0.7477641075510757 and parameters: {'n_estimators': 1700, 'learning_rate': 0.012891334307964486, 'max_depth': 7, 'subsample': 0.569175842596809, 'colsample_bytree': 0.55383513709829, 'reg_alpha': 6.108497343480775, 'reg_lambda': 0.0012008380871718696}. Best is trial 3 with value: 0.7477641075510757.
[I 2025-12-17 07:12:15,717] Trial 4 finished with value: 0.6733048766034943 and parameters: {'n_estimators': 1200, 'learning_rate': 0.031200202396948155, 'max_depth': 3, 'subsample': 0.6051165052879596, 'colsample_bytree': 0.5723350768748443, 'reg_alpha': 0.9450368293587498, 'reg_lambda': 0.2098271953405504}. Best is trial 3 with value: 0.7477641075510757.
[I 2025-12-17 07:12:17,914] Trial 5 finished with value: 0.20708936240961676 and parameters: {'n_estimators': 500, 'learning_rate': 0.0010807261133347111, 'max_depth': 9, 'subsample': 0.8195383664422577, 'colsample_bytree': 0.8876173156270668, 'reg_alpha': 0.0024226947734446226, 'reg_lambda': 0.0258029535190891}. Best is trial 3 with value: 0.7477641075510757.
[I 2025-12-17 07:12:19,784] Trial 6 finished with value: 0.7104988451319544 and parameters: {'n_estimators': 500, 'learning_rate': 0.004154512309069082, 'max_depth': 5, 'subsample': 0.6847360379769564, 'colsample_bytree': 0.8193872642182154, 'reg_alpha': 0.08579346014776869, 'reg_lambda': 0.0022013852080692044}. Best is trial 3 with value: 0.7477641075510757.
[I 2025-12-17 07:12:25,048] Trial 7 finished with value: 0.7879325221910823 and parameters: {'n_estimators': 2000, 'learning_rate': 0.004080735332062982, 'max_depth': 3, 'subsample': 0.888185252735701, 'colsample_bytree': 0.7962557029385009, 'reg_alpha': 0.3314136970626266, 'reg_lambda': 0.06093228645445554}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:28,042] Trial 8 finished with value: 0.6051826144784754 and parameters: {'n_estimators': 1200, 'learning_rate': 0.036870020277358424, 'max_depth': 7, 'subsample': 0.670883944049165, 'colsample_bytree': 0.7553479895731108, 'reg_alpha': 0.15564178557277386, 'reg_lambda': 0.0002068197208692801}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:31,344] Trial 9 finished with value: 0.6391839747597258 and parameters: {'n_estimators': 1800, 'learning_rate': 0.06218348668448093, 'max_depth': 9, 'subsample': 0.5535322008988869, 'colsample_bytree': 0.7306002145427555, 'reg_alpha': 9.665633933306479, 'reg_lambda': 0.06318124682967062}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:36,546] Trial 10 finished with value: 0.4728669213260339 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005048292148254505, 'max_depth': 3, 'subsample': 0.8888738106689551, 'colsample_bytree': 0.8974027079292205, 'reg_alpha': 0.01369593307973439, 'reg_lambda': 5.314706652943647}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:41,190] Trial 11 finished with value: 0.6657809126208906 and parameters: {'n_estimators': 1600, 'learning_rate': 0.009211912557341457, 'max_depth': 7, 'subsample': 0.5030798491677464, 'colsample_bytree': 0.6600500554015478, 'reg_alpha': 0.8041893224746705, 'reg_lambda': 0.0030506105068580027}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:45,804] Trial 12 finished with value: 0.7221998724528765 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017401117206626415, 'max_depth': 6, 'subsample': 0.7728852041089047, 'colsample_bytree': 0.5247497043476074, 'reg_alpha': 0.9731821007971578, 'reg_lambda': 0.0027689291663718016}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:51,142] Trial 13 finished with value: 0.7475039155097001 and parameters: {'n_estimators': 1500, 'learning_rate': 0.004874363519093885, 'max_depth': 8, 'subsample': 0.6121659767528036, 'colsample_bytree': 0.7894074741867494, 'reg_alpha': 0.28183625640441695, 'reg_lambda': 0.014365953704281424}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:52,841] Trial 14 finished with value: 0.7829205699985868 and parameters: {'n_estimators': 900, 'learning_rate': 0.14530905823302984, 'max_depth': 5, 'subsample': 0.6086451004891422, 'colsample_bytree': 0.5003850267825519, 'reg_alpha': 0.0001514669198236647, 'reg_lambda': 0.0011856053512060928}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:54,567] Trial 15 finished with value: 0.7300052968517065 and parameters: {'n_estimators': 900, 'learning_rate': 0.1457197314392341, 'max_depth': 5, 'subsample': 0.7368762984788704, 'colsample_bytree': 0.6611018580288315, 'reg_alpha': 0.006464344774737747, 'reg_lambda': 0.8297078253321654}. Best is trial 7 with value: 0.7879325221910823.
[I 2025-12-17 07:12:56,221] Trial 16 finished with value: 0.862274274787823 and parameters: {'n_estimators': 900, 'learning_rate': 0.1364220608561147, 'max_depth': 4, 'subsample': 0.8362240313802416, 'colsample_bytree': 0.8387178484885438, 'reg_alpha': 0.00010198481280673212, 'reg_lambda': 0.010392122551168646}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:00,831] Trial 17 finished with value: 0.8048070238818719 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0026312794190406492, 'max_depth': 4, 'subsample': 0.8389618238118157, 'colsample_bytree': 0.8375727376798419, 'reg_alpha': 0.00011413314772312591, 'reg_lambda': 0.008609808219513819}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:05,426] Trial 18 finished with value: 0.7577378161065532 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0020197975645462264, 'max_depth': 4, 'subsample': 0.8335421989177949, 'colsample_bytree': 0.849502775936513, 'reg_alpha': 0.00021742494683155614, 'reg_lambda': 0.009929245704272017}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:06,398] Trial 19 finished with value: 0.7697550241018271 and parameters: {'n_estimators': 300, 'learning_rate': 0.0813573690804045, 'max_depth': 6, 'subsample': 0.8222443938035393, 'colsample_bytree': 0.8467673444211054, 'reg_alpha': 0.00034907508606671367, 'reg_lambda': 0.006842286565070959}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:08,990] Trial 20 finished with value: 0.756877634630539 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02294734598607721, 'max_depth': 4, 'subsample': 0.8522535601624708, 'colsample_bytree': 0.7689581813640965, 'reg_alpha': 0.00010459857092517384, 'reg_lambda': 0.0005355525215305017}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:12,505] Trial 21 finished with value: 0.7552900296136046 and parameters: {'n_estimators': 1300, 'learning_rate': 0.0019345932235330704, 'max_depth': 3, 'subsample': 0.8974352034519059, 'colsample_bytree': 0.8181406021787883, 'reg_alpha': 0.03790240264401347, 'reg_lambda': 0.07430793035957471}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:15,248] Trial 22 finished with value: 0.8267575637703705 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007346048697886766, 'max_depth': 3, 'subsample': 0.7750002696460803, 'colsample_bytree': 0.8460477389115533, 'reg_alpha': 0.0006681652224263274, 'reg_lambda': 0.05250521038746459}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:18,490] Trial 23 finished with value: 0.3762960833080746 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007798308744851264, 'max_depth': 4, 'subsample': 0.7759171742773692, 'colsample_bytree': 0.8608033472096933, 'reg_alpha': 0.000532346447341869, 'reg_lambda': 0.237744473254448}. Best is trial 16 with value: 0.862274274787823.
[I 2025-12-17 07:13:21,180] Trial 24 finished with value: 0.7418607646904573 and parameters: {'n_estimators': 700, 'learning_rate': 0.002779359050691043, 'max_depth': 5, 'subsample': 0.7385212175118233, 'colsample_bytree': 0.8204941771978673, 'reg_alpha': 0.0023128062087250964, 'reg_lambda': 0.020510776200848724}. Best is trial 16 with value: 0.862274274787823.

Best R2: 0.8623
Saved -> xgb_state_3_Dry_Green_g.pkl

All state-specific models trained and saved successfully.